// Diese Datei wurde automatisch generiert. Bitte nicht manuell bearbeiten.
// Zuletzt generiert: 2025-05-09T04:09:46.451Z

export const ortschaftZuKanton: Record<string, Kanton> = {
  "Aadorf": "TG",
  "Aarau": "AG",
  "Aarau Rohr": "AG",
  "Aarberg": "BE",
  "Aarburg": "AG",
  "Aarwangen": "BE",
  "Aathal-Seegräben": "ZH",
  "Aawangen": "TG",
  "Abländschen": "BE",
  "Abtwil AG": "AG",
  "Abtwil SG": "SG",
  "Achseten": "BE",
  "Aclens": "VD",
  "Acquarossa": "TI",
  "Adelboden": "BE",
  "Adetswil": "ZH",
  "Adligenswil": "LU",
  "Adlikon b. Andelfingen": "ZH",
  "Adlikon b. Regensdorf": "ZH",
  "Adliswil": "ZH",
  "Aedermannsdorf": "SO",
  "Aefligen": "BE",
  "Aegerten": "BE",
  "Aesch (Neftenbach)": "ZH",
  "Aesch BL": "BL",
  "Aesch LU": "LU",
  "Aesch ZH": "ZH",
  "Aeschau": "BE",
  "Aeschi b. Spiez": "BE",
  "Aeschi SO": "SO",
  "Aeschiried": "BE",
  "Aeschlen b. Oberdiessbach": "BE",
  "Aeschlen ob Gunten": "BE",
  "Aetigkofen": "SO",
  "Aetingen": "SO",
  "Aettenschwil": "AG",
  "Aeugst am Albis": "ZH",
  "Aeugstertal": "ZH",
  "Affeltrangen": "TG",
  "Affoltern am Albis": "ZH",
  "Affoltern im Emmental": "BE",
  "Agarn": "VS",
  "Agarone": "TI",
  "Agasul": "ZH",
  "Agiez": "VD",
  "Agno": "TI",
  "Agra": "TI",
  "Agriswil": "FR",
  "Aigle": "VD",
  "Aïre": "GE",
  "Aire-la-Ville": "GE",
  "Airolo": "TI",
  "Alberswil": "LU",
  "Albeuve": "FR",
  "Albinen": "VS",
  "Albligen": "BE",
  "Alchenflüh": "BE",
  "Alchenstorf": "BE",
  "Aldesago": "TI",
  "Algetshausen": "SG",
  "Alikon": "AG",
  "Allaman": "VD",
  "Alle": "JU",
  "Allens": "VD",
  "Allenwinden": "ZG",
  "Allerheiligenberg": "SO",
  "Allmendingen b. Bern": "BE",
  "Allschwil": "BL",
  "Almens": "GR",
  "Alosen": "ZG",
  "Alp Grüm": "GR",
  "Alpnach Dorf": "OW",
  "Alpnachstad": "OW",
  "Alpthal": "SZ",
  "Altbüron": "LU",
  "Altdorf SH": "SH",
  "Altdorf UR": "UR",
  "Alten": "ZH",
  "Altendorf": "SZ",
  "Altenrhein": "SG",
  "Alterswil FR": "FR",
  "Alterswilen": "TG",
  "Altikon": "ZH",
  "Altishausen": "TG",
  "Altishofen": "LU",
  "Altnau": "TG",
  "Altstätten SG": "SG",
  "Altwis": "LU",
  "Alvaneu Bad": "GR",
  "Alvaneu Dorf": "GR",
  "Alvaschein": "GR",
  "Am Bach (Avers)": "GR",
  "Ambrì": "TI",
  "Amden": "SG",
  "Aminona": "VS",
  "Amlikon-Bissegg": "TG",
  "Ammerswil AG": "AG",
  "Ammerzwil BE": "BE",
  "Amriswil": "TG",
  "Amsoldingen": "BE",
  "Amsteg": "UR",
  "Andeer": "GR",
  "Andelfingen": "ZH",
  "Andermatt": "UR",
  "Andhausen": "TG",
  "Andiast": "GR",
  "Andwil SG": "SG",
  "Andwil TG": "TG",
  "Anglikon": "AG",
  "Anières": "GE",
  "Anwil": "BL",
  "Anzère": "VS",
  "Anzonico": "TI",
  "Appenzell": "AI",
  "Appenzell Eggerstanden": "AI",
  "Appenzell Enggenhütten": "AI",
  "Appenzell Meistersrüte": "AI",
  "Appenzell Schlatt": "AI",
  "Appenzell Steinegg": "AI",
  "Apples": "VD",
  "Aproz (Nendaz)": "VS",
  "Aquila": "TI",
  "Aran": "VD",
  "Aranno": "TI",
  "Arbaz": "VS",
  "Arbedo": "TI",
  "Arboldswil": "BL",
  "Arbon": "TG",
  "Arcegno": "TI",
  "Arch": "BE",
  "Arconciel": "FR",
  "Ardez": "GR",
  "Ardon": "VS",
  "Areuse": "NE",
  "Arezen": "GR",
  "Argnoud (Ayent)": "VS",
  "Arisdorf": "BL",
  "Aristau": "AG",
  "Arlesheim": "BL",
  "Arnegg": "SG",
  "Arnex-sur-Nyon": "VD",
  "Arnex-sur-Orbe": "VD",
  "Arni AG": "AG",
  "Arni BE": "BE",
  "Arogno": "TI",
  "Arolla": "VS",
  "Arosa": "GR",
  "Arosio": "TI",
  "Arth": "SZ",
  "Arveyes": "VD",
  "Arvigo": "GR",
  "Arvillard (Salins)": "VS",
  "Arzier": "VD",
  "Arzo": "TI",
  "Ascharina": "GR",
  "Ascona": "TI",
  "Asp": "AG",
  "Assens": "VD",
  "Astano": "TI",
  "Asuel": "JU",
  "Athenaz (Avusy)": "GE",
  "Attalens": "FR",
  "Attelwil": "AG",
  "Attikon": "ZH",
  "Attinghausen": "UR",
  "Attiswil": "BE",
  "Au SG": "SG",
  "Au TG": "TG",
  "Au ZH": "ZH",
  "Aubonne": "VD",
  "Auboranges": "FR",
  "Auddes-sur-Riddes": "VS",
  "Auenstein": "AG",
  "Augio": "GR",
  "Augst BL": "BL",
  "Aumont": "FR",
  "Auressio": "TI",
  "Aurigeno": "TI",
  "Auslikon": "ZH",
  "Ausserberg": "VS",
  "Ausserbinn": "VS",
  "Ausserferrera": "GR",
  "Auswil": "BE",
  "Autafond": "FR",
  "Autavaux": "FR",
  "Autigny": "FR",
  "Auvernier": "NE",
  "Auw": "AG",
  "Avegno": "TI",
  "Aven": "VS",
  "Avenches": "VD",
  "Avry-Centre FR": "FR",
  "Avry-devant-Pont": "FR",
  "Avry-sur-Matran": "FR",
  "Avully": "GE",
  "Axalp": "BE",
  "Ayer": "VS",
  "Azmoos": "SG",
  "Baar": "ZG",
  "Baar (Nendaz)": "VS",
  "Bäch SZ": "SZ",
  "Bachenbülach": "ZH",
  "Bachs": "ZH",
  "Bad Ragaz": "SG",
  "Bad Zurzach": "AG",
  "Baden": "AG",
  "Baldegg": "LU",
  "Baldingen": "AG",
  "Balerna": "TI",
  "Balgach": "SG",
  "Ballaigues": "VD",
  "Ballens": "VD",
  "Ballmoos": "BE",
  "Ballwil": "LU",
  "Balm b. Günsberg": "SO",
  "Balm b. Messen": "SO",
  "Balmberg": "SO",
  "Balsthal": "SO",
  "Balterswil": "TG",
  "Baltschieder": "VS",
  "Balzers": "FL",
  "Banco": "TI",
  "Bangerten b. Dieterswil": "BE",
  "Bänk (Dägerlen)": "ZH",
  "Bannwil": "BE",
  "Bärau": "BE",
  "Barbengo": "TI",
  "Barberêche": "FR",
  "Bäretswil": "ZH",
  "Bargen BE": "BE",
  "Bargen SH": "SH",
  "Bäriswil BE": "BE",
  "Barmelweid": "AG",
  "Bärschwil": "SO",
  "Barzheim": "SH",
  "Basadingen": "TG",
  "Basel": "BS",
  "Basel Universitätsspital": "BS",
  "Basse-Nendaz": "VS",
  "Bassecourt": "JU",
  "Bassersdorf": "ZH",
  "Bassins": "VD",
  "Bätterkinden": "BE",
  "Bättwil": "SO",
  "Bauen": "UR",
  "Baulmes": "VD",
  "Bauma": "ZH",
  "Bavois": "VD",
  "Bazenheid": "SG",
  "Beatenberg": "BE",
  "Beckenried": "NW",
  "Bedano": "TI",
  "Bedigliora": "TI",
  "Bedretto": "TI",
  "Beggingen": "SH",
  "Begnins": "VD",
  "Beinwil (Freiamt)": "AG",
  "Beinwil am See": "AG",
  "Beinwil SO": "SO",
  "Belalp": "VS",
  "Belfaux": "FR",
  "Bellach": "SO",
  "Bellelay": "BE",
  "Bellerive VD": "VD",
  "Bellevue": "GE",
  "Bellikon": "AG",
  "Bellinzona": "TI",
  "Bellmund": "BE",
  "Bellwald": "VS",
  "Belmont-sur-Lausanne": "VD",
  "Belmont-sur-Yverdon": "VD",
  "Belp": "BE",
  "Belpberg": "BE",
  "Belprahon": "BE",
  "Benglen": "ZH",
  "Benken SG": "SG",
  "Benken ZH": "ZH",
  "Bennau": "SZ",
  "Bennwil": "BL",
  "Benzenschwil": "AG",
  "Bercher": "VD",
  "Berg (Dägerlen)": "ZH",
  "Berg am Irchel": "ZH",
  "Berg SG": "SG",
  "Berg TG": "TG",
  "Bergdietikon": "AG",
  "Bergün/Bravuogn": "GR",
  "Berikon": "AG",
  "Beringen": "SH",
  "Berken": "BE",
  "Berlens": "FR",
  "Berlingen": "TG",
  "Bern": "BE",
  "Berneck": "SG",
  "Bernex": "GE",
  "Bernhardzell": "SG",
  "Berolle": "VD",
  "Beromünster": "LU",
  "Berschis": "SG",
  "Bertschikon": "ZH",
  "Bertschikon (Gossau ZH)": "ZH",
  "Berzona": "TI",
  "Besazio": "TI",
  "Besenbüren": "AG",
  "Besencens": "FR",
  "Betschwanden": "GL",
  "Betten": "VS",
  "Bettenhausen": "BE",
  "Bettens": "VD",
  "Bettingen": "BS",
  "Bettlach": "SO",
  "Bettmeralp": "VS",
  "Bettwiesen": "TG",
  "Bettwil": "AG",
  "Beurnevésin": "JU",
  "Beuson (Nendaz)": "VS",
  "Bevaix": "NE",
  "Bever": "GR",
  "Bévilard": "BE",
  "Bex": "VD",
  "Biasca": "TI",
  "Biasca Stazione": "TI",
  "Biberen": "BE",
  "Biberist": "SO",
  "Bibern SH": "SH",
  "Bibern SO": "SO",
  "Biberstein": "AG",
  "Bichelsee": "TG",
  "Bichwil": "SG",
  "Bidogno": "TI",
  "Biel VS": "VS",
  "Biel-Benken BL": "BL",
  "Biel/Bienne": "BE",
  "Biembach im Emmental": "BE",
  "Bière": "VD",
  "Bieudron (Nendaz)": "VS",
  "Biezwil": "SO",
  "Bigenthal": "BE",
  "Biglen": "BE",
  "Bignasco": "TI",
  "Bigorio": "TI",
  "Billens": "FR",
  "Bilten": "GL",
  "Binn": "VS",
  "Binningen": "BL",
  "Binz": "ZH",
  "Bioggio": "TI",
  "Biogno-Beride": "TI",
  "Bioley-de-Brignon (Nendaz)": "VS",
  "Bioley-Magnoux": "VD",
  "Bioley-Orjulaz": "VD",
  "Bionnens": "FR",
  "Birgisch": "VS",
  "Birmensdorf ZH": "ZH",
  "Birmenstorf AG": "AG",
  "Bironico": "TI",
  "Birr": "AG",
  "Birrhard": "AG",
  "Birrwil": "AG",
  "Birsfelden": "BL",
  "Birwinken": "TG",
  "Bischofszell": "TG",
  "Bisisthal": "SZ",
  "Bissone": "TI",
  "Bister": "VS",
  "Bitsch": "VS",
  "Bivio": "GR",
  "Blankenburg": "BE",
  "Blatten (Lötschen)": "VS",
  "Blatten b. Naters": "VS",
  "Blauen": "BL",
  "Blausee-Mitholz": "BE",
  "Bleienbach": "BE",
  "Bleiken b. Oberdiessbach": "BE",
  "Blessens": "FR",
  "Blignoud (Ayent)": "VS",
  "Blitzingen": "VS",
  "Blonay": "VD",
  "Blumenstein": "BE",
  "Böbikon": "AG",
  "Böckten": "BL",
  "Bodio TI": "TI",
  "Boécourt": "JU",
  "Bofflens": "VD",
  "Bogis-Bossey": "VD",
  "Bogno": "TI",
  "Bôle": "NE",
  "Bolken": "SO",
  "Boll": "BE",
  "Bolligen": "BE",
  "Bollingen": "SG",
  "Bollion": "FR",
  "Bollodingen": "BE",
  "Boltigen": "BE",
  "Bombinasco": "TI",
  "Bonaduz": "GR",
  "Bonau": "TG",
  "Boncourt": "JU",
  "Bonfol": "JU",
  "Bönigen b. Interlaken": "BE",
  "Boningen": "SO",
  "Boniswil": "AG",
  "Bonnefontaine": "FR",
  "Bonstetten": "ZH",
  "Bonvillars": "VD",
  "Boppelsen": "ZH",
  "Borex": "VD",
  "Borgnone": "TI",
  "Borgonovo": "GR",
  "Bosco Luganese": "TI",
  "Bosco/Gurin": "TI",
  "Bösingen": "FR",
  "Bossonnens": "FR",
  "Boswil": "AG",
  "Bottens": "VD",
  "Bottenwil": "AG",
  "Botterens": "FR",
  "Bottighofen": "TG",
  "Bottmingen": "BL",
  "Böttstein": "AG",
  "Botyre (Ayent)": "VS",
  "Boudevilliers": "NE",
  "Boudry": "NE",
  "Bougy-Villars": "VD",
  "Boulens": "VD",
  "Bouloz": "FR",
  "Bourg-St-Pierre": "VS",
  "Bourguillon": "FR",
  "Bournens": "VD",
  "Bourrignon": "JU",
  "Boussens": "VD",
  "Bouveret": "VS",
  "Boveresse": "NE",
  "Bovernier": "VS",
  "Bowil": "BE",
  "Bözen": "AG",
  "Braggio": "GR",
  "Brail": "GR",
  "Bramboden": "LU",
  "Bramois": "VS",
  "Bratsch": "VS",
  "Braunau": "TG",
  "Braunwald": "GL",
  "Brè sopra Lugano": "TI",
  "Breganzona": "TI",
  "Breil/Brigels": "GR",
  "Breitenbach": "SO",
  "Bremblens": "VD",
  "Bremgarten AG": "AG",
  "Bremgarten b. Bern": "BE",
  "Brenles": "VD",
  "Breno": "TI",
  "Brent": "VD",
  "Brenzikofen": "BE",
  "Bressaucourt": "JU",
  "Bretigny-sur-Morrens": "VD",
  "Bretonnières": "VD",
  "Bretzwil": "BL",
  "Brienz BE": "BE",
  "Brienz/Brinzauls GR": "GR",
  "Brienzwiler": "BE",
  "Brig": "VS",
  "Brigerbad": "VS",
  "Brignon (Nendaz)": "VS",
  "Brione (Verzasca)": "TI",
  "Brione sopra Minusio": "TI",
  "Brislach": "BL",
  "Brissago": "TI",
  "Bristen": "UR",
  "Brittern": "SO",
  "Brittnau": "AG",
  "Broc": "FR",
  "Broglio": "TI",
  "Bronschhofen": "SG",
  "Brontallo": "TI",
  "Brot-Dessous": "NE",
  "Brot-Plamboz": "NE",
  "Bruderholz": "BL",
  "Brugg AG": "AG",
  "Brügg BE": "BE",
  "Brügglen": "SO",
  "Brülisau": "AI",
  "Brunegg": "AG",
  "Brünig": "BE",
  "Brünisried": "FR",
  "Brunnadern": "SG",
  "Brunnen": "SZ",
  "Brunnenthal": "SO",
  "Brusino Arsizio": "TI",
  "Brusio": "GR",
  "Bruson": "VS",
  "Brüttelen": "BE",
  "Brütten": "ZH",
  "Brüttisellen": "ZH",
  "Bruzella": "TI",
  "Bubendorf": "BL",
  "Bubikon": "ZH",
  "Buch am Irchel": "ZH",
  "Buch b. Frauenfeld": "TG",
  "Buch b. Kümmertshausen": "TG",
  "Buch b. Märwil": "TG",
  "Buch SH": "SH",
  "Buchackern": "TG",
  "Buchberg": "SH",
  "Buchen BE": "BE",
  "Buchen im Prättigau": "GR",
  "Buchillon": "VD",
  "Buchrain": "LU",
  "Buchs AG": "AG",
  "Buchs LU": "LU",
  "Buchs SG": "SG",
  "Buchs ZH": "ZH",
  "Büchslen": "FR",
  "Buckten": "BL",
  "Büetigen": "BE",
  "Bühl b. Aarberg": "BE",
  "Bühler": "AR",
  "Buhwil": "TG",
  "Buix": "JU",
  "Bülach": "ZH",
  "Bulle": "FR",
  "Bullet": "VD",
  "Bünzen": "AG",
  "Buochs": "NW",
  "Buonas": "ZG",
  "Bürchen": "VS",
  "Bure": "JU",
  "Büren an der Aare": "BE",
  "Büren NW": "NW",
  "Büren SO": "SO",
  "Büren zum Hof": "BE",
  "Burg AG": "AG",
  "Burg im Leimental": "BL",
  "Burgäschi": "SO",
  "Burgdorf": "BE",
  "Bürgenstock": "NW",
  "Burgistein": "BE",
  "Burglauenen": "BE",
  "Bürglen OW": "OW",
  "Bürglen TG": "TG",
  "Bürglen UR": "UR",
  "Büriswilen": "AI",
  "Büron": "LU",
  "Bursinel": "VD",
  "Bursins": "VD",
  "Burtigny": "VD",
  "Buseno": "GR",
  "Büsserach": "SO",
  "Bussigny-près-Lausanne": "VD",
  "Bussigny-sur-Oron": "VD",
  "Bussnang": "TG",
  "Busswil b. Büren": "BE",
  "Busswil b. Melchnau": "BE",
  "Busswil TG": "TG",
  "Bussy FR": "FR",
  "Bussy-Chardonney": "VD",
  "Bussy-sur-Moudon": "VD",
  "Büttenhardt": "SH",
  "Buttes": "NE",
  "Büttikon AG": "AG",
  "Buttikon SZ": "SZ",
  "Buttisholz": "LU",
  "Buttwil": "AG",
  "Bützberg": "BE",
  "Buus": "BL",
  "Cabbio": "TI",
  "Cademario": "TI",
  "Cadempino": "TI",
  "Cadenazzo": "TI",
  "Cadro": "TI",
  "Cagiallo": "TI",
  "Calfreisen": "GR",
  "Calonico": "TI",
  "Calpiogna": "TI",
  "Cama": "GR",
  "Camedo": "TI",
  "Camignolo": "TI",
  "Camischolas": "GR",
  "Camorino": "TI",
  "Campascio": "GR",
  "Campello": "TI",
  "Camperio": "TI",
  "Campo (Blenio)": "TI",
  "Campo (Vallemaggia)": "TI",
  "Campocologno": "GR",
  "Campsut-Cröt": "GR",
  "Camuns": "GR",
  "Caneggio": "TI",
  "Canobbio": "TI",
  "Capolago": "TI",
  "Carabbia": "TI",
  "Carabietta": "TI",
  "Carena": "TI",
  "Carì": "TI",
  "Carona": "TI",
  "Carouge GE": "GE",
  "Carrera": "GR",
  "Carrouge VD": "VD",
  "Cartigny": "GE",
  "Casaccia": "GR",
  "Casima": "TI",
  "Caslano": "TI",
  "Cassina d'Agno": "TI",
  "Castagnola": "TI",
  "Castaneda": "GR",
  "Castasegna": "GR",
  "Castel San Pietro": "TI",
  "Castelrotto": "TI",
  "Castiel": "GR",
  "Castione": "TI",
  "Castrisch": "GR",
  "Castro": "TI",
  "Cauco": "GR",
  "Caux": "VD",
  "Cavagnago": "TI",
  "Cavardiras": "GR",
  "Cavergno": "TI",
  "Caviano": "TI",
  "Cavigliano": "TI",
  "Cazis": "GR",
  "Celerina/Schlarigna": "GR",
  "Céligny": "GE",
  "Cerentino": "TI",
  "Cerniat FR": "FR",
  "Cerniaz VD": "VD",
  "Cernier": "NE",
  "Certara": "TI",
  "Cevio": "TI",
  "Châbles FR": "FR",
  "Chabrey": "VD",
  "Chailly-Montreux": "VD",
  "Chalais": "VS",
  "Cham": "ZG",
  "Chambésy": "GE",
  "Chamblon": "VD",
  "Chambrelien": "NE",
  "Chamby": "VD",
  "Chamoille (Sembrancher)": "VS",
  "Chamoson": "VS",
  "Champ-du-Moulin": "NE",
  "Champagne": "VD",
  "Champéry": "VS",
  "Champex-Lac": "VS",
  "Champfèr": "GR",
  "Champlan (Grimisuat)": "VS",
  "Champoussin": "VS",
  "Champoz": "BE",
  "Champsec (Versegères)": "VS",
  "Champtauroz": "VD",
  "Champvent": "VD",
  "Champzabé": "VS",
  "Chancy": "GE",
  "Chandolin": "VS",
  "Chandolin-près-Savièse": "VS",
  "Chandon": "FR",
  "Chandonne (Liddes)": "VS",
  "Chanéaz": "VD",
  "Chapelle (Broye)": "FR",
  "Chapelle (Glâne)": "FR",
  "Chapelle-sur-Moudon": "VD",
  "Chardonne": "VD",
  "Charmey (Gruyère)": "FR",
  "Charmoille": "JU",
  "Charrat": "VS",
  "Château-d'Oex": "VD",
  "Châtel-St-Denis": "FR",
  "Châtel-sur-Montsalvens": "FR",
  "Châtelaine": "GE",
  "Châtelat": "BE",
  "Châtillens": "VD",
  "Châtillon FR": "FR",
  "Châtillon JU": "JU",
  "Châtonnaye": "FR",
  "Chaumont": "NE",
  "Chavannes-de-Bogis": "VD",
  "Chavannes-des-Bois": "VD",
  "Chavannes-le-Chêne": "VD",
  "Chavannes-le-Veyron": "VD",
  "Chavannes-les-Forts": "FR",
  "Chavannes-près-Renens": "VD",
  "Chavannes-sous-Orsonnens": "FR",
  "Chavannes-sur-Moudon": "VD",
  "Chavornay": "VD",
  "Cheiry": "FR",
  "Chemin": "VS",
  "Chenaux": "VD",
  "Chêne-Bougeries": "GE",
  "Chêne-Bourg": "GE",
  "Chêne-Pâquier": "VD",
  "Chénens": "FR",
  "Chermignon": "VS",
  "Chermignon-d'en-Bas": "VS",
  "Chernex": "VD",
  "Chesalles-sur-Moudon": "VD",
  "Chesalles-sur-Oron": "VD",
  "Cheseaux-Noréaz": "VD",
  "Cheseaux-sur-Lausanne": "VD",
  "Chéserex": "VD",
  "Chesières": "VD",
  "Chésopelloz": "FR",
  "Chessel": "VD",
  "Chevenez": "JU",
  "Chevilly": "VD",
  "Chevroux": "VD",
  "Chexbres": "VD",
  "Cheyres": "FR",
  "Chez Petit (Liddes)": "VS",
  "Chez-le-Bart": "NE",
  "Chézard-St-Martin": "NE",
  "Chiasso": "TI",
  "Chiggiogna": "TI",
  "Chigny": "VD",
  "Chippis": "VS",
  "Chironico": "TI",
  "Choëx": "VS",
  "Choulex": "GE",
  "Chur": "GR",
  "Churwalden": "GR",
  "Cimadera": "TI",
  "Cimalmotto": "TI",
  "Cimo": "TI",
  "Cinuos-chel": "GR",
  "Clarens": "VD",
  "Clarmont": "VD",
  "Claro": "TI",
  "Clavaleyres": "BE",
  "Clèbes (Nendaz)": "VS",
  "Clugin": "GR",
  "Coeuve": "JU",
  "Coffrane": "NE",
  "Coglio": "TI",
  "Coinsins": "VD",
  "Cointrin": "GE",
  "Coldrerio": "TI",
  "Colla": "TI",
  "Collex": "GE",
  "Collombey": "VS",
  "Collonge-Bellerive": "GE",
  "Collonges": "VS",
  "Cologny": "GE",
  "Colombier NE": "NE",
  "Colombier VD": "VD",
  "Comano": "TI",
  "Combremont-le-Grand": "VD",
  "Combremont-le-Petit": "VD",
  "Coméraz (Grimisuat)": "VS",
  "Commugny": "VD",
  "Comologno": "TI",
  "Conches": "GE",
  "Concise": "VD",
  "Condémines (Nendaz)": "VS",
  "Confignon": "GE",
  "Constantine": "VD",
  "Conters im Prättigau": "GR",
  "Conthey": "VS",
  "Contone": "TI",
  "Contra": "TI",
  "Coppet": "VD",
  "Corban": "JU",
  "Corbeyrier": "VD",
  "Corbières": "FR",
  "Corcelles BE": "BE",
  "Corcelles NE": "NE",
  "Corcelles-le-Jorat": "VD",
  "Corcelles-près-Concise": "VD",
  "Corcelles-près-Payerne": "VD",
  "Corcelles-sur-Chavornay": "VD",
  "Cordast": "FR",
  "Corgémont": "BE",
  "Corin-de-la-Crête": "VS",
  "Corippo": "TI",
  "Corjolens": "FR",
  "Cormagens": "FR",
  "Cormérod": "FR",
  "Corminboeuf": "FR",
  "Cormondrèche": "NE",
  "Cormoret": "BE",
  "Cornaux NE": "NE",
  "Cornol": "JU",
  "Corpataux-Magnedens": "FR",
  "Correvon": "VD",
  "Corseaux": "VD",
  "Corserey": "FR",
  "Corsier GE": "GE",
  "Corsier-sur-Vevey": "VD",
  "Cortaillod": "NE",
  "Cortébert": "BE",
  "Corteglia": "TI",
  "Corticiasca": "TI",
  "Corzoneso": "TI",
  "Cossonay-Ville": "VD",
  "Cottens FR": "FR",
  "Cottens VD": "VD",
  "Cotterd": "VD",
  "Cotterg (Le Châble VS)": "VS",
  "Courcelon": "JU",
  "Courchapoix": "JU",
  "Courchavon": "JU",
  "Courfaivre": "JU",
  "Courgenay": "JU",
  "Courgevaux": "FR",
  "Courlevon": "FR",
  "Cournillens": "FR",
  "Courrendlin": "JU",
  "Courroux": "JU",
  "Court": "BE",
  "Courtaman": "FR",
  "Courtedoux": "JU",
  "Courtelary": "BE",
  "Courtemaîche": "JU",
  "Courtemautruy": "JU",
  "Courtepin": "FR",
  "Courtételle": "JU",
  "Courtion": "FR",
  "Cousset": "FR",
  "Couvet": "NE",
  "Cozzo": "TI",
  "Crana": "TI",
  "Crans-Montana": "VS",
  "Crans-près-Céligny": "VD",
  "Crassier": "VD",
  "Cremin": "VD",
  "Crémines": "BE",
  "Cresciano": "TI",
  "Cressier FR": "FR",
  "Cressier NE": "NE",
  "Cresta (Avers)": "GR",
  "Crésuz": "FR",
  "Crête-à-l'Oeil(Les Agettes)": "VS",
  "Cries (Vollèges)": "VS",
  "Crissier": "VD",
  "Cronay": "VD",
  "Croy": "VD",
  "Crusch": "GR",
  "Cuarnens": "VD",
  "Cuarny": "VD",
  "Cudrefin": "VD",
  "Cugnasco": "TI",
  "Cugy FR": "FR",
  "Cugy VD": "VD",
  "Cully": "VD",
  "Cumbel": "GR",
  "Cumpadials": "GR",
  "Cunter": "GR",
  "Curaglia": "GR",
  "Cureggia": "TI",
  "Cureglia": "TI",
  "Curio": "TI",
  "Curtilles": "VD",
  "Curtina": "TI",
  "Dachsen": "ZH",
  "Dägerlen": "ZH",
  "Dagmersellen": "LU",
  "Daillens": "VD",
  "Daillon": "VS",
  "Daiwil": "LU",
  "Dalin": "GR",
  "Dallenwil": "NW",
  "Dällikon": "ZH",
  "Dalpe": "TI",
  "Damphreux": "JU",
  "Damvant": "JU",
  "Dangio-Torre": "TI",
  "Däniken SO": "SO",
  "Dänikon ZH": "ZH",
  "Danis": "GR",
  "Dardagny": "GE",
  "Dardin": "GR",
  "Därligen": "BE",
  "Därstetten": "BE",
  "Dättlikon": "ZH",
  "Dättwil AG": "AG",
  "Davesco-Soragno": "TI",
  "Davos Clavadel": "GR",
  "Davos Dorf": "GR",
  "Davos Frauenkirch": "GR",
  "Davos Glaris": "GR",
  "Davos Monstein": "GR",
  "Davos Platz": "GR",
  "Davos Wolfgang": "GR",
  "Degen": "GR",
  "Degersheim": "SG",
  "Deisswil b. Münchenbuchsee": "BE",
  "Deitingen": "SO",
  "Delémont": "JU",
  "Delley": "FR",
  "Démoret": "VD",
  "Denens": "VD",
  "Denezy": "VD",
  "Denges": "VD",
  "Densbüren": "AG",
  "Derendingen": "SO",
  "Detligen": "BE",
  "Dettighofen": "TG",
  "Develier": "JU",
  "Dicken": "SG",
  "Diegten": "BL",
  "Dielsdorf": "ZH",
  "Diemerswil": "BE",
  "Diemtigen": "BE",
  "Diepflingen": "BL",
  "Diepoldsau": "SG",
  "Dierikon": "LU",
  "Diesbach GL": "GL",
  "Diessbach b. Büren": "BE",
  "Diesse": "BE",
  "Diessenhofen": "TG",
  "Dieterswil": "BE",
  "Dietikon": "ZH",
  "Dietlikon": "ZH",
  "Dietwil": "AG",
  "Dinhard": "ZH",
  "Dino": "TI",
  "Dintikon": "AG",
  "Disentis/Mustér": "GR",
  "Dittingen": "BL",
  "Dizy": "VD",
  "Domat/Ems": "GR",
  "Dombresson": "NE",
  "Domdidier": "FR",
  "Dommartin": "VD",
  "Dompierre FR": "FR",
  "Dompierre VD": "VD",
  "Donat": "GR",
  "Donatyre": "VD",
  "Dongio": "TI",
  "Donneloye": "VD",
  "Donzhausen": "TG",
  "Doppleschwand": "LU",
  "Dorénaz": "VS",
  "Dorf": "ZH",
  "Dörflingen": "SH",
  "Dornach": "SO",
  "Dotnacht": "TG",
  "Dottikon": "AG",
  "Döttingen": "AG",
  "Dotzigen": "BE",
  "Dozwil": "TG",
  "Dranse (Liddes)": "VS",
  "Drône VS": "VS",
  "Dübendorf": "ZH",
  "Düdingen": "FR",
  "Duggingen": "BL",
  "Dugny (Leytron)": "VS",
  "Duillier": "VD",
  "Dulliken": "SO",
  "Dully": "VD",
  "Dürnten": "ZH",
  "Dürrenäsch": "AG",
  "Dürrenroth": "BE",
  "Dussnang": "TG",
  "Duvin": "GR",
  "Ebersecken": "LU",
  "Ebersol": "SG",
  "Ebertswil": "ZH",
  "Ebikon": "LU",
  "Ebmatingen": "ZH",
  "Ebnet": "LU",
  "Echallens": "VD",
  "Echandens": "VD",
  "Echarlens": "FR",
  "Echichens": "VD",
  "Eclagnens": "VD",
  "Eclépens": "VD",
  "Ecoteaux": "VD",
  "Ecublens FR": "FR",
  "Ecublens VD": "VD",
  "Ecuvillens": "FR",
  "Ederswiler": "JU",
  "Edlibach": "ZG",
  "Effingen": "AG",
  "Effretikon": "ZH",
  "Egerkingen": "SO",
  "Egg (Flawil)": "SG",
  "Egg b. Zürich": "ZH",
  "Egg SZ": "SZ",
  "Eggenwil": "AG",
  "Eggerberg": "VS",
  "Eggersriet": "SG",
  "Eggethof": "TG",
  "Eggiwil": "BE",
  "Eglisau": "ZH",
  "Egliswil": "AG",
  "Egnach": "TG",
  "Egolzwil": "LU",
  "Ehrendingen": "AG",
  "Eich": "LU",
  "Eichberg": "SG",
  "Eigenthal": "LU",
  "Eigergletscher": "BE",
  "Eiken": "AG",
  "Einigen": "BE",
  "Einsiedeln": "SZ",
  "Eischoll": "VS",
  "Eison (St.Martin)": "VS",
  "Eisten": "VS",
  "Elfingen": "AG",
  "Elgg": "ZH",
  "Ellighausen": "TG",
  "Ellikon am Rhein": "ZH",
  "Ellikon an der Thur": "ZH",
  "Elm": "GL",
  "Elsau": "ZH",
  "Embd": "VS",
  "Embrach": "ZH",
  "Emdthal": "BE",
  "Emmen": "LU",
  "Emmenbrücke": "LU",
  "Emmenmatt": "BE",
  "Emmetten": "NW",
  "Endingen": "AG",
  "Engelberg": "OW",
  "Engelburg": "SG",
  "Enges": "NE",
  "Enggistein": "BE",
  "Engi": "GL",
  "Engishofen": "TG",
  "Englisberg": "BE",
  "Engollon": "NE",
  "Engwang": "TG",
  "Engwilen": "TG",
  "Ennenda": "GL",
  "Ennetaach": "TG",
  "Ennetbaden": "AG",
  "Ennetbürgen": "NW",
  "Ennetmoos": "NW",
  "Enney": "FR",
  "Entlebuch": "LU",
  "Epagny": "FR",
  "Epalinges": "VD",
  "Epautheyres": "VD",
  "Epauvillers": "JU",
  "Ependes FR": "FR",
  "Ependes VD": "VD",
  "Epesses": "VD",
  "Epiquerez": "JU",
  "Eppenberg": "SO",
  "Epsach": "BE",
  "Eptingen": "BL",
  "Erde": "VS",
  "Ergisch": "VS",
  "Eriswil": "BE",
  "Eriz": "BE",
  "Erlach": "BE",
  "Erlen": "TG",
  "Erlenbach im Simmental": "BE",
  "Erlenbach ZH": "ZH",
  "Erlinsbach": "AG",
  "Erlinsbach SO": "SO",
  "Ermatingen": "TG",
  "Ermensee": "LU",
  "Ermenswil": "SG",
  "Ernen": "VS",
  "Ernetschwil": "SG",
  "Erschmatt": "VS",
  "Erschwil": "SO",
  "Ersigen": "BE",
  "Erstfeld": "UR",
  "Eschen": "FL",
  "Eschenbach LU": "LU",
  "Eschenbach SG": "SG",
  "Eschenz": "TG",
  "Eschert": "BE",
  "Eschikofen": "TG",
  "Eschlikon TG": "TG",
  "Escholzmatt": "LU",
  "Esmonts": "FR",
  "Essert FR": "FR",
  "Essert-Pittet": "VD",
  "Essert-sous-Champvent": "VD",
  "Essertes": "VD",
  "Essertines-sur-Rolle": "VD",
  "Essertines-sur-Yverdon": "VD",
  "Esslingen": "ZH",
  "Estavannens": "FR",
  "Estavayer-le-Gibloux": "FR",
  "Estavayer-le-Lac": "FR",
  "Estévenens": "FR",
  "Etagnières": "VD",
  "Etoy": "VD",
  "Ettenhausen TG": "TG",
  "Ettingen": "BL",
  "Ettiswil": "LU",
  "Etzelkofen": "BE",
  "Etzgen": "AG",
  "Etziken": "SO",
  "Etzwilen": "TG",
  "Euseigne": "VS",
  "Euthal": "SZ",
  "Evilard": "BE",
  "Evionnaz": "VS",
  "Evolène": "VS",
  "Eyholz": "VS",
  "Eysins": "VD",
  "Fahrni b. Thun": "BE",
  "Fahrwangen": "AG",
  "Fahrweid": "ZH",
  "Fahy": "JU",
  "Faido": "TI",
  "Fajauna": "GR",
  "Falera": "GR",
  "Fällanden": "ZH",
  "Faltigberg": "ZH",
  "Fanas": "GR",
  "Fankhaus (Trub)": "BE",
  "Faoug": "VD",
  "Farden": "GR",
  "Farnern": "BE",
  "Farvagny": "FR",
  "Farvagny-le-Petit": "FR",
  "Faulensee": "BE",
  "Féchy": "VD",
  "Fehraltorf": "ZH",
  "Fehren": "SO",
  "Felben-Wellhausen": "TG",
  "Feldbach": "ZH",
  "Feldbrunnen": "SO",
  "Feldis/Veulden": "GR",
  "Felsberg": "GR",
  "Felsenau AG": "AG",
  "Fenalet-sur-Bex": "VD",
  "Fenil-sur-Corsier": "VD",
  "Fenin": "NE",
  "Fenkrieden": "AG",
  "Ferden": "VS",
  "Ferenbalm": "BE",
  "Ferlens VD": "VD",
  "Ferpicloz": "FR",
  "Ferreyres": "VD",
  "Fescoggia": "TI",
  "Fétigny": "FR",
  "Feuerthalen": "ZH",
  "Feusisberg": "SZ",
  "Feutersoey": "BE",
  "Fex": "GR",
  "Fey": "VD",
  "Fey (Nendaz)": "VS",
  "Fiaugères": "FR",
  "Fidaz": "GR",
  "Fideris": "GR",
  "Fiesch": "VS",
  "Fieschertal": "VS",
  "Fiez": "VD",
  "Figino": "TI",
  "Filet": "VS",
  "Filisur": "GR",
  "Filzbach": "GL",
  "Finhaut": "VS",
  "Finsterhennen": "BE",
  "Finstersee": "ZG",
  "Finsterwald b. Entlebuch": "LU",
  "Fionnay": "VS",
  "Fischbach LU": "LU",
  "Fischbach-Göslikon": "AG",
  "Fischenthal": "ZH",
  "Fischingen": "TG",
  "Fisibach": "AG",
  "Fislisbach": "AG",
  "Flaach": "ZH",
  "Flamatt": "FR",
  "Flanthey": "VS",
  "Fläsch": "GR",
  "Flawil": "SG",
  "Flendruz": "VD",
  "Flerden": "GR",
  "Fleurier": "NE",
  "Flims Dorf": "GR",
  "Flims Waldhaus": "GR",
  "Flond": "GR",
  "Flüelen": "UR",
  "Flüeli-Ranft": "OW",
  "Flüh": "SO",
  "Flühli LU": "LU",
  "Flumenthal": "SO",
  "Flums": "SG",
  "Flums Hochwiese": "SG",
  "Flumserberg Bergheim": "SG",
  "Flumserberg Portels": "SG",
  "Flumserberg Saxli": "SG",
  "Flumserberg Tannenbodenalp": "SG",
  "Flumserberg Tannenheim": "SG",
  "Flurlingen": "ZH",
  "Font": "FR",
  "Fontaine Dessous (Liddes)": "VS",
  "Fontaine Dessus (Liddes)": "VS",
  "Fontainemelon": "NE",
  "Fontaines NE": "NE",
  "Fontaines-sur-Grandson": "VD",
  "Fontanezier": "VD",
  "Fontannen b. Wolhusen": "LU",
  "Fontenais": "JU",
  "Fontenelle (Le Châble VS)": "VS",
  "Fontnas": "SG",
  "Forch": "ZH",
  "Forel (Lavaux)": "VD",
  "Forel FR": "FR",
  "Forel-sur-Lucens": "VD",
  "Formangueires": "FR",
  "Fornet-Dessous": "BE",
  "Fornet-Dessus": "JU",
  "Fornex (Liddes)": "VS",
  "Forst b. Längenbühl": "BE",
  "Fortunau (Ayent)": "VS",
  "Founex": "VD",
  "Fräschels": "FR",
  "Frasco": "TI",
  "Frasnacht": "TG",
  "Frasses": "FR",
  "Fraubrunnen": "BE",
  "Frauenfeld": "TG",
  "Frauenkappelen": "BE",
  "Fregiécourt": "JU",
  "Freidorf TG": "TG",
  "Freienbach": "SZ",
  "Freienstein": "ZH",
  "Freienwil": "AG",
  "Freimettigen": "BE",
  "Frenières-sur-Bex": "VD",
  "Frenkendorf": "BL",
  "Fresens": "NE",
  "Fretereules": "NE",
  "Freudwil": "ZH",
  "Fribourg": "FR",
  "Frick": "AG",
  "Frieswil": "BE",
  "Friltschen": "TG",
  "Frinvillier": "BE",
  "Froideville": "VD",
  "Frümsen": "SG",
  "Fruthwilen": "TG",
  "Frutigen": "BE",
  "Ftan": "GR",
  "Fuldera": "GR",
  "Fulenbach": "SO",
  "Full-Reuenthal": "AG",
  "Füllinsdorf": "BL",
  "Fully": "VS",
  "Fürigen": "NW",
  "Furna": "GR",
  "Fürstenau": "GR",
  "Fürstenaubruck": "GR",
  "Fusio": "TI",
  "Gabi (Simplon)": "VS",
  "Gächlingen": "SH",
  "Gächliwil": "SO",
  "Gachnang": "TG",
  "Gadenstätt": "GR",
  "Gadmen": "BE",
  "Gähwil": "SG",
  "Gais": "AR",
  "Galgenen": "SZ",
  "Gallenkirch": "AG",
  "Galmiz": "FR",
  "Gals": "BE",
  "Gammen": "BE",
  "Gampel": "VS",
  "Gampelen": "BE",
  "Gamprin-Bendern": "FL",
  "Gams": "SG",
  "Gamsen": "VS",
  "Gandria": "TI",
  "Gänsbrunnen": "SO",
  "Gansingen": "AG",
  "Gasel": "BE",
  "Gasenried": "VS",
  "Gattikon": "ZH",
  "Gebenstorf": "AG",
  "Gebertingen": "SG",
  "Geiss": "LU",
  "Gelfingen": "LU",
  "Gelterfingen": "BE",
  "Gelterkinden": "BL",
  "Geltwil": "AG",
  "Gempen": "SO",
  "Gempenach": "FR",
  "Genestrerio": "TI",
  "Genève": "GE",
  "Genève 15 Aéroport": "GE",
  "Genolier": "VD",
  "Genthod": "GE",
  "Gentilino": "TI",
  "Gerlafingen": "SO",
  "Gerlikon": "TG",
  "Geroldswil": "ZH",
  "Gerolfingen": "BE",
  "Gerra (Gambarogno)": "TI",
  "Gerra (Verzasca)": "TI",
  "Gersau": "SZ",
  "Gerzensee": "BE",
  "Geschinen": "VS",
  "Gettnau": "LU",
  "Geuensee": "LU",
  "Ghirone": "TI",
  "Gibswil-Ried": "ZH",
  "Giebenach": "BL",
  "Giez": "VD",
  "Giffers": "FR",
  "Gillarens": "FR",
  "Gilly": "VD",
  "Gimel": "VD",
  "Gimmelwald": "BE",
  "Gingins": "VD",
  "Giornico": "TI",
  "Gipf-Oberfrick": "AG",
  "Gisikon": "LU",
  "Giswil": "OW",
  "Giubiasco": "TI",
  "Giumaglio": "TI",
  "Givisiez": "FR",
  "Givrins": "VD",
  "Gland": "VD",
  "Glarus": "GL",
  "Glashütten": "AG",
  "Glaspass": "GR",
  "Glattbrugg": "ZH",
  "Glattfelden": "ZH",
  "Glattpark (Opfikon)": "ZH",
  "Gletterens": "FR",
  "Glion": "VD",
  "Glis": "VS",
  "Glovelier": "JU",
  "Gluringen": "VS",
  "Gnosca": "TI",
  "Gockhausen": "ZH",
  "Gohl": "BE",
  "Golaten": "BE",
  "Goldach": "SG",
  "Goldau": "SZ",
  "Goldingen": "SG",
  "Goldiwil (Thun)": "BE",
  "Goldswil b. Interlaken": "BE",
  "Golino": "TI",
  "Gollion": "VD",
  "Gommiswald": "SG",
  "Gondiswil": "BE",
  "Gondo": "VS",
  "Gonten": "AI",
  "Gontenbad": "AI",
  "Gontenschwil": "AG",
  "Goppenstein": "VS",
  "Goppisberg": "VS",
  "Gordevio": "TI",
  "Gordola": "TI",
  "Gorduno": "TI",
  "Gorgier": "NE",
  "Göschenen": "UR",
  "Gossau SG": "SG",
  "Gossau ZH": "ZH",
  "Gossens": "VD",
  "Gossliwil": "SO",
  "Götighofen": "TG",
  "Gottlieben": "TG",
  "Goumoens-la-Ville": "VD",
  "Goumoens-le-Jux": "VD",
  "Goumois": "JU",
  "Graben": "BE",
  "Grabs": "SG",
  "Grabserberg": "SG",
  "Grächen": "VS",
  "Grafenort": "OW",
  "Grafenried": "BE",
  "Grafstal": "ZH",
  "Graltshausen": "TG",
  "Grancia": "TI",
  "Grancy": "VD",
  "Grand-Lancy": "GE",
  "Grandcour": "VD",
  "Grandevent": "VD",
  "Grandfontaine": "JU",
  "Grandsivaz": "FR",
  "Grandson": "VD",
  "Grandval": "BE",
  "Grandvaux": "VD",
  "Grandvillard": "FR",
  "Granges (Veveyse)": "FR",
  "Granges VS": "VS",
  "Granges-de-Vesin": "FR",
  "Granges-Paccot": "FR",
  "Granges-près-Marnand": "VD",
  "Grangettes-près-Romont": "FR",
  "Gränichen": "AG",
  "Granois (Savièse)": "VS",
  "Gräslikon": "ZH",
  "Grasswil": "BE",
  "Grattavache": "FR",
  "Gravesano": "TI",
  "Greich": "VS",
  "Greifensee": "ZH",
  "Grellingen": "BL",
  "Grenchen": "SO",
  "Greng": "FR",
  "Grengiols": "VS",
  "Grenilles": "FR",
  "Grens": "VD",
  "Greppen": "LU",
  "Gresso": "TI",
  "Gressy": "VD",
  "Gretschins": "SG",
  "Gretzenbach": "SO",
  "Grimentz": "VS",
  "Grimisuat": "VS",
  "Grindel": "SO",
  "Grindelwald": "BE",
  "Grolley": "FR",
  "Grône": "VS",
  "Grono": "GR",
  "Gross": "SZ",
  "Grossaffoltern": "BE",
  "Grossdietwil": "LU",
  "Grosshöchstetten": "BE",
  "Grosswangen": "LU",
  "Grub AR": "AR",
  "Grub SG": "SG",
  "Gruben": "VS",
  "Grugnay (Chamoson)": "VS",
  "Grund b. Gstaad": "BE",
  "Grünen": "BE",
  "Grünenmatt": "BE",
  "Grüningen": "ZH",
  "Grüsch": "GR",
  "Grüt (Gossau ZH)": "ZH",
  "Gruyères": "FR",
  "Gryon": "VD",
  "Gstaad": "BE",
  "Gsteig b. Gstaad": "BE",
  "Gsteigwiler": "BE",
  "Guarda": "GR",
  "Gudo": "TI",
  "Guggisberg": "BE",
  "Gumefens": "FR",
  "Gümligen": "BE",
  "Gümmenen": "BE",
  "Gundetswil": "ZH",
  "Gündlischwand": "BE",
  "Günsberg": "SO",
  "Guntalingen": "ZH",
  "Gunten": "BE",
  "Guntershausen b. Aadorf": "TG",
  "Guntershausen b. Berg": "TG",
  "Gunterswilen": "TG",
  "Guntmadingen": "SH",
  "Gunzgen": "SO",
  "Gunzwil": "LU",
  "Gurbrü": "BE",
  "Gurmels": "FR",
  "Gurtnellen": "UR",
  "Gurzelen": "BE",
  "Guschelmuth": "FR",
  "Gutenburg": "BE",
  "Gutenswil": "ZH",
  "Guttannen": "BE",
  "Guttet-Feschel": "VS",
  "Güttingen": "TG",
  "Gwatt (Thun)": "BE",
  "Gy": "GE",
  "Gysenstein": "BE",
  "Haag (Rheintal)": "SG",
  "Habkern": "BE",
  "Habsburg": "AG",
  "Häfelfingen": "BL",
  "Hagenbuch ZH": "ZH",
  "Hägendorf": "SO",
  "Hagendorn": "ZG",
  "Hagenwil b. Amriswil": "TG",
  "Häggenschwil": "SG",
  "Hägglingen": "AG",
  "Hagneck": "BE",
  "Halden": "TG",
  "Haldenstein": "GR",
  "Haldi b. Schattdorf": "UR",
  "Hallau": "SH",
  "Hallwil": "AG",
  "Halten": "SO",
  "Hämikon": "LU",
  "Happerswil": "TG",
  "Harenwilen": "TG",
  "Härkingen": "SO",
  "Hasle b. Burgdorf": "BE",
  "Hasle LU": "LU",
  "Haslen AI": "AI",
  "Haslen GL": "GL",
  "Hasliberg Goldern": "BE",
  "Hasliberg Hohfluh": "BE",
  "Hasliberg Reuti": "BE",
  "Hasliberg Wasserwendi": "BE",
  "Hattenhausen": "TG",
  "Hätzingen": "GL",
  "Hauenstein": "SO",
  "Hauptikon": "ZH",
  "Hauptwil": "TG",
  "Hausen AG": "AG",
  "Hausen am Albis": "ZH",
  "Häusernmoos im Emmental": "BE",
  "Häuslenen": "TG",
  "Haute-Nendaz": "VS",
  "Hauterive NE": "NE",
  "Hauteville": "FR",
  "Häutligen": "BE",
  "Hedingen": "ZH",
  "Heerbrugg": "SG",
  "Hefenhausen": "TG",
  "Hefenhofen": "TG",
  "Heiden": "AR",
  "Heiligenschwendi": "BE",
  "Heiligkreuz (Mels)": "SG",
  "Heimberg": "BE",
  "Heimenhausen": "BE",
  "Heimenschwand": "BE",
  "Heimisbach": "BE",
  "Heimiswil": "BE",
  "Heinrichswil": "SO",
  "Heitenried": "FR",
  "Heldswil": "TG",
  "Helgisried-Rohrbach": "BE",
  "Hellbühl": "LU",
  "Hellikon": "AG",
  "Hellsau": "BE",
  "Hemishofen": "SH",
  "Hemmental": "SH",
  "Hemmiken": "BL",
  "Henau": "SG",
  "Hendschiken": "AG",
  "Henggart": "ZH",
  "Hennens": "FR",
  "Henniez": "VD",
  "Herbetswil": "SO",
  "Herbligen": "BE",
  "Herbriggen": "VS",
  "Herdern": "TG",
  "Hérémence": "VS",
  "Hergiswil b. Willisau": "LU",
  "Hergiswil NW": "NW",
  "Herisau": "AR",
  "Herlisberg": "LU",
  "Hermance": "GE",
  "Hermatswil": "ZH",
  "Hermenches": "VD",
  "Hermetschwil-Staffeln": "AG",
  "Hermiswil": "BE",
  "Hermrigen": "BE",
  "Herrenhof": "TG",
  "Herrenschwanden": "BE",
  "Herrliberg": "ZH",
  "Hersberg": "BL",
  "Hersiwil": "SO",
  "Hertenstein AG": "AG",
  "Herznach": "AG",
  "Herzogenbuchsee": "BE",
  "Hessigkofen": "SO",
  "Hettenschwil": "AG",
  "Hettiswil b. Hindelbank": "BE",
  "Hettlingen": "ZH",
  "Hildisrieden": "LU",
  "Hilfikon": "AG",
  "Hilterfingen": "BE",
  "Himmelried": "SO",
  "Hindelbank": "BE",
  "Hinteregg": "ZH",
  "Hinterforst": "SG",
  "Hinterfultigen": "BE",
  "Hinterkappelen": "BE",
  "Hintermoos": "LU",
  "Hinterrhein": "GR",
  "Hinwil": "ZH",
  "Hirschthal": "AG",
  "Hirzel": "ZH",
  "Hittnau": "ZH",
  "Hitzkirch": "LU",
  "Hochdorf": "LU",
  "Hochfelden": "ZH",
  "Höchstetten": "BE",
  "Hochwald": "SO",
  "Höfen b. Thun": "BE",
  "Hofen SH": "SH",
  "Hoffeld": "SG",
  "Hofstatt": "LU",
  "Hofstetten b. Brienz": "BE",
  "Hofstetten SO": "SO",
  "Hofstetten ZH": "ZH",
  "Hohenrain": "LU",
  "Hohentannen": "TG",
  "Hohtenn": "VS",
  "Holderbank AG": "AG",
  "Holderbank SO": "SO",
  "Hölstein": "BL",
  "Holzhäusern ZG": "ZG",
  "Holziken": "AG",
  "Homberg b. Thun": "BE",
  "Hombrechtikon": "ZH",
  "Homburg": "TG",
  "Honau": "LU",
  "Hondrich": "BE",
  "Horboden": "BE",
  "Horgen": "ZH",
  "Horgenberg": "ZH",
  "Hörhausen": "TG",
  "Höri": "ZH",
  "Horn": "TG",
  "Hornussen": "AG",
  "Horrenbach": "BE",
  "Horriwil": "SO",
  "Horw": "LU",
  "Hosenruck": "TG",
  "Hospental": "UR",
  "Hottwil": "AG",
  "Hubersdorf": "SO",
  "Huémoz": "VD",
  "Hugelshofen": "TG",
  "Humlikon": "ZH",
  "Hundwil": "AR",
  "Hünenberg": "ZG",
  "Hünenberg See": "ZG",
  "Hünibach": "BE",
  "Hüniken": "SO",
  "Hünikon (Neftenbach)": "ZH",
  "Hüntwangen": "ZH",
  "Hunzenschwil": "AG",
  "Hurden": "SZ",
  "Hüswil": "LU",
  "Hütten": "ZH",
  "Hüttikon": "ZH",
  "Hüttlingen": "TG",
  "Huttwil": "BE",
  "Hüttwilen": "TG",
  "Ibach": "SZ",
  "Ichertswil": "SO",
  "Icogne": "VS",
  "Iffwil": "BE",
  "Igis": "GR",
  "Ilanz": "GR",
  "Illgau": "SZ",
  "Illhart": "TG",
  "Illighausen": "TG",
  "Illnau": "ZH",
  "Im Fang": "FR",
  "Immensee": "SZ",
  "Indemini": "TI",
  "Inden": "VS",
  "Inkwil": "BE",
  "Innerberg": "BE",
  "Innereriz": "BE",
  "Innerferrera": "GR",
  "Innerthal": "SZ",
  "Innertkirchen": "BE",
  "Ins": "BE",
  "Insone": "TI",
  "Interlaken": "BE",
  "Intragna": "TI",
  "Intschi": "UR",
  "Inwil": "LU",
  "Ipsach": "BE",
  "Iragna": "TI",
  "Iseltwald": "BE",
  "Isenfluh": "BE",
  "Isenthal": "UR",
  "Iseo": "TI",
  "Isérables": "VS",
  "Islikon": "TG",
  "Islisberg": "AG",
  "Isole di Brissago": "TI",
  "Isone": "TI",
  "Istighofen": "TG",
  "Itingen": "BL",
  "Ittenthal": "AG",
  "Ittigen": "BE",
  "Jaberg": "BE",
  "Jakobsbad": "AI",
  "Jaun": "FR",
  "Jegenstorf": "BE",
  "Jenaz": "GR",
  "Jenins": "GR",
  "Jens": "BE",
  "Jeuss": "FR",
  "Jona": "SG",
  "Jonen": "AG",
  "Jongny": "VD",
  "Jonschwil": "SG",
  "Jouxtens-Mézery": "VD",
  "Juf": "GR",
  "Jungfraujoch": "VS",
  "Juriens": "VD",
  "Jussy": "GE",
  "Kägiswil": "OW",
  "Kaiseraugst": "AG",
  "Kaiserstuhl AG": "AG",
  "Kaisten": "AG",
  "Kallern": "AG",
  "Kallnach": "BE",
  "Kalpetran": "VS",
  "Kaltacker": "BE",
  "Kaltbach": "LU",
  "Kaltbrunn": "SG",
  "Kaltenbach": "TG",
  "Kammersrohr": "SO",
  "Kandergrund": "BE",
  "Kandersteg": "BE",
  "Känerkinden": "BL",
  "Kappel am Albis": "ZH",
  "Kappel SO": "SO",
  "Kappelen": "BE",
  "Kastanienbaum": "LU",
  "Kaufdorf": "BE",
  "Kefikon TG": "TG",
  "Kefikon ZH": "ZH",
  "Kehrsatz": "BE",
  "Kehrsiten": "NW",
  "Kemptthal": "ZH",
  "Kernenried": "BE",
  "Kerns": "OW",
  "Kerzers": "FR",
  "Kesswil": "TG",
  "Kestenholz": "SO",
  "Kienberg": "SO",
  "Kienersrüti": "BE",
  "Kiental": "BE",
  "Kiesen": "BE",
  "Kilchberg BL": "BL",
  "Kilchberg ZH": "ZH",
  "Killwangen": "AG",
  "Kippel": "VS",
  "Kirchberg BE": "BE",
  "Kirchberg SG": "SG",
  "Kirchdorf AG": "AG",
  "Kirchdorf BE": "BE",
  "Kirchenthurnen": "BE",
  "Kirchleerau": "AG",
  "Kirchlindach": "BE",
  "Klarsreuti": "TG",
  "Kleinandelfingen": "ZH",
  "Kleinbösingen": "FR",
  "Kleindietwil": "BE",
  "Kleindöttingen": "AG",
  "Kleine Scheidegg": "BE",
  "Kleingurmels": "FR",
  "Kleinlützel": "SO",
  "Kleinwangen": "LU",
  "Klingnau": "AG",
  "Klöntal": "GL",
  "Kloster Fahr": "AG",
  "Klosters": "GR",
  "Klosters Dorf": "GR",
  "Kloten": "ZH",
  "Knoblisbühl": "SG",
  "Knonau": "ZH",
  "Knutwil": "LU",
  "Koblenz": "AG",
  "Kollbrunn": "ZH",
  "Kölliken": "AG",
  "Köniz": "BE",
  "Konolfingen": "BE",
  "Koppigen": "BE",
  "Kottwil": "LU",
  "Kradolf": "TG",
  "Kräiligen": "BE",
  "Krattigen": "BE",
  "Krauchthal": "BE",
  "Kreuzlingen": "TG",
  "Kriechenwil": "BE",
  "Kriegstetten": "SO",
  "Kriens": "LU",
  "Kriessern": "SG",
  "Küblis": "GR",
  "Kulmerau": "LU",
  "Kümmertshausen": "TG",
  "Künten": "AG",
  "Küsnacht ZH": "ZH",
  "Küssnacht am Rigi": "SZ",
  "Küttigen": "AG",
  "Küttigkofen": "SO",
  "Kyburg": "ZH",
  "Kyburg-Buchegg": "SO",
  "L'Abbaye": "VD",
  "L'Abergement": "VD",
  "L'Auberson": "VD",
  "L'Etivaz": "VD",
  "L'Isle": "VD",
  "La Brévine": "NE",
  "La Châtagne": "NE",
  "La Chaux (Cossonay)": "VD",
  "La Chaux-de-Fonds": "NE",
  "La Chaux-des-Breuleux": "JU",
  "La Chaux-du-Milieu": "NE",
  "La Cibourg": "BE",
  "La Comballaz": "VD",
  "La Conversion": "VD",
  "La Corbaz": "FR",
  "La Côte-aux-Fées": "NE",
  "La Coudre": "VD",
  "La Croix (Lutry)": "VD",
  "La Croix-de-Rozon": "GE",
  "La Cure": "VD",
  "La Ferrière": "BE",
  "La Forclaz VD": "VD",
  "La Fouly VS": "VS",
  "La Garde (Sembrancher)": "VS",
  "La Heutte": "BE",
  "La Joux FR": "FR",
  "La Lécherette": "VD",
  "La Magne": "FR",
  "La Montoz (Versegères)": "VS",
  "La Neirigue": "FR",
  "La Neuveville": "BE",
  "La Place (Ayent)": "VS",
  "La Plaine": "GE",
  "La Praz": "VD",
  "La Punt-Chamues-ch": "GR",
  "La Rippe": "VD",
  "La Roche FR": "FR",
  "La Rösa": "GR",
  "La Russille": "VD",
  "La Sage": "VS",
  "La Sagne (Ste-Croix)": "VD",
  "La Sagne NE": "NE",
  "La Sarraz": "VD",
  "La Tanne": "BE",
  "La Tine": "VD",
  "La Tour-de-Peilz": "VD",
  "La Tour-de-Trême": "FR",
  "La Tzoumaz": "VS",
  "La Vernaz (Les Agettes)": "VS",
  "La Verrerie": "FR",
  "La Vraconnaz": "VD",
  "La Vue-des-Alpes": "NE",
  "Laax GR": "GR",
  "Laax GR 2": "GR",
  "Lachen SZ": "SZ",
  "Laconnex": "GE",
  "Ladir": "GR",
  "Lajoux JU": "JU",
  "Lalden": "VS",
  "Lamboing": "BE",
  "Lamone": "TI",
  "Lampenberg": "BL",
  "Lamperswil TG": "TG",
  "Lana (Evolène)": "VS",
  "Landquart": "GR",
  "Landschlacht": "TG",
  "Langenbruck": "BL",
  "Längenbühl": "BE",
  "Langendorf": "SO",
  "Langenthal": "BE",
  "Langnau am Albis": "ZH",
  "Langnau b. Reiden": "LU",
  "Langnau im Emmental": "BE",
  "Langrickenbach": "TG",
  "Langwies": "GR",
  "Langwiesen": "ZH",
  "Lanterswil": "TG",
  "Lantsch/Lenz": "GR",
  "Lanzenhäusern": "BE",
  "Lanzenneunforn": "TG",
  "Largario": "TI",
  "Latsch": "GR",
  "Latterbach": "BE",
  "Lätti": "BE",
  "Lauenen b. Gstaad": "BE",
  "Lauerz": "SZ",
  "Läufelfingen": "BL",
  "Laufen": "BL",
  "Laufenburg": "AG",
  "Laupen BE": "BE",
  "Laupen ZH": "ZH",
  "Laupersdorf": "SO",
  "Lauperswil": "BE",
  "Laura": "GR",
  "Lausanne": "VD",
  "Lausen": "BL",
  "Lauterbrunnen": "BE",
  "Lauwil": "BL",
  "Lavertezzo": "TI",
  "Lavey-les-Bains": "VD",
  "Lavey-Village": "VD",
  "Lavigny": "VD",
  "Lavin": "GR",
  "Lavorgo": "TI",
  "Lax": "VS",
  "Le Bémont": "JU",
  "Le Bémont JU": "JU",
  "Le Brassus": "VD",
  "Le Brouillet": "NE",
  "Le Bry": "FR",
  "Le Cerneux-Péquignot": "NE",
  "Le Cerneux-Veusil": "JU",
  "Le Châble VS": "VS",
  "Le Château-de-Ste-Croix": "VD",
  "Le Châtelard VS": "VS",
  "Le Châtelard-près-Romont": "FR",
  "Le Crêt-du-Locle": "NE",
  "Le Crêt-près-Semsales": "FR",
  "Le Fregnoley (Versegères)": "VS",
  "Le Fuet": "BE",
  "Le Grand-Saconnex": "GE",
  "Le Jordil": "FR",
  "Le Landeron": "NE",
  "Le Lieu": "VD",
  "Le Lignon": "GE",
  "Le Locle": "NE",
  "Le Mont-Pèlerin": "VD",
  "Le Mont-sur-Lausanne": "VD",
  "Le Morgnes (Lourtier)": "VS",
  "Le Mouret": "FR",
  "Le Muids": "VD",
  "Le Noirmont": "JU",
  "Le Pâquier NE": "NE",
  "Le Pâquier-Montbarry": "FR",
  "Le Planchamp (Lourtier)": "VS",
  "Le Pont": "VD",
  "Le Prédame": "JU",
  "Le Prese": "GR",
  "Le Prévoux": "NE",
  "Le Sentier": "VD",
  "Le Sépey": "VD",
  "Le Solliat": "VD",
  "Le Trétien": "VS",
  "Le Vaud": "VD",
  "Léchelles": "FR",
  "Leggia": "GR",
  "Leibstadt": "AG",
  "Leimbach AG": "AG",
  "Leimbach TG": "TG",
  "Leimiswil": "BE",
  "Leissigen": "BE",
  "Lenggenwil": "SG",
  "Lengnau AG": "AG",
  "Lengnau BE": "BE",
  "Lengwil-Oberhofen": "TG",
  "Lenk im Simmental": "BE",
  "Lens": "VS",
  "Lentigny": "FR",
  "Lenzburg": "AG",
  "Lenzerheide/Lai": "GR",
  "Leontica": "TI",
  "Les Acacias": "GE",
  "Les Agettes": "VS",
  "Les Avanchets": "GE",
  "Les Avants": "VD",
  "Les Bayards": "NE",
  "Les Bioux": "VD",
  "Les Bois": "JU",
  "Les Brenets": "NE",
  "Les Breuleux": "JU",
  "Les Charbonnières": "VD",
  "Les Clées": "VD",
  "Les Collons": "VS",
  "Les Crosets": "VS",
  "Les Cullayes": "VD",
  "Les Diablerets": "VD",
  "Les Ecasseys": "FR",
  "Les Ecorcheresses": "BE",
  "Les Emibois": "JU",
  "Les Enfers": "JU",
  "Les Evouettes": "VS",
  "Les Friques": "FR",
  "Les Geneveys-sur-Coffrane": "NE",
  "Les Genevez JU": "JU",
  "Les Giettes": "VS",
  "Les Granges (Salvan)": "VS",
  "Les Hauts-Geneveys": "NE",
  "Les Joux-Derrière": "NE",
  "Les Marécottes": "VS",
  "Les Mayens-de-Sion": "VS",
  "Les Monts-de-Corsier": "VD",
  "Les Monts-de-Pully": "VD",
  "Les Mosses": "VD",
  "Les Moulins": "VD",
  "Les Moulins VS (Liddes)": "VS",
  "Les Paccots": "FR",
  "Les Places (Versegères)": "VS",
  "Les Planchettes": "NE",
  "Les Plans-sur-Bex": "VD",
  "Les Pommerats": "JU",
  "Les Pontins": "BE",
  "Les Ponts-de-Martel": "NE",
  "Les Posses-sur-Bex": "VD",
  "Les Prés-d'Orvin": "BE",
  "Les Rasses": "VD",
  "Les Reussilles": "BE",
  "Les Sagnettes": "NE",
  "Les Sciernes-d'Albeuve": "FR",
  "Les Taillères": "NE",
  "Les Tavernes": "VD",
  "Les Thioleyres": "VD",
  "Les Valettes (Bovernier)": "VS",
  "Les Vérines (Chamoson)": "VS",
  "Les Verrières": "NE",
  "Les Vieux-Prés": "NE",
  "Lessoc": "FR",
  "Leuggelbach": "GL",
  "Leuggern": "AG",
  "Leuk Stadt": "VS",
  "Leukerbad": "VS",
  "Leutwil": "AG",
  "Leuzigen": "BE",
  "Levron": "VS",
  "Leysin": "VD",
  "Leytron": "VS",
  "Li Curt": "GR",
  "Liddes": "VS",
  "Liebefeld": "BE",
  "Liebistorf": "FR",
  "Liedertswil": "BL",
  "Lieffrens": "FR",
  "Lieli LU": "LU",
  "Lienz": "SG",
  "Liesberg": "BL",
  "Liesberg Dorf": "BL",
  "Liestal": "BL",
  "Liez (St-Martin)": "VS",
  "Ligerz": "BE",
  "Lignerolle": "VD",
  "Lignières": "NE",
  "Ligornetto": "TI",
  "Limpach": "BE",
  "Lindau": "ZH",
  "Linden": "BE",
  "Linescio": "TI",
  "Linn": "AG",
  "Linthal": "GL",
  "Lipperswil": "TG",
  "Lippoldswilen": "TG",
  "Littenheid": "TG",
  "Litzirüti": "GR",
  "Lobsigen": "BE",
  "Loc": "VS",
  "Locarno": "TI",
  "Loco": "TI",
  "Lodano": "TI",
  "Lodrino": "TI",
  "Lohn GR": "GR",
  "Lohn SH": "SH",
  "Lohn-Ammannsegg": "SO",
  "Löhningen": "SH",
  "Lohnstorf": "BE",
  "Lömmenschwil": "SG",
  "Lommis": "TG",
  "Lommiswil": "SO",
  "Lonay": "VD",
  "Longirod": "VD",
  "Lopagno": "TI",
  "Losone": "TI",
  "Lossy": "FR",
  "Lostallo": "GR",
  "Lostorf": "SO",
  "Lottigna": "TI",
  "Lotzwil": "BE",
  "Lourtier": "VS",
  "Lovatens": "VD",
  "Lovens": "FR",
  "Loveresse": "BE",
  "Lü": "GR",
  "Luc (Ayent)": "VS",
  "Lucelle": "JU",
  "Lucens": "VD",
  "Lüchingen": "SG",
  "Luchsingen": "GL",
  "Ludiano": "TI",
  "Lüen": "GR",
  "Lufingen": "ZH",
  "Lugaggia": "TI",
  "Lugano": "TI",
  "Lugnez": "JU",
  "Lugnorre": "FR",
  "Luins": "VD",
  "Lully FR": "FR",
  "Lully VD": "VD",
  "Lumbrein": "GR",
  "Lumino": "TI",
  "Lungern": "OW",
  "Lupfig": "AG",
  "Lupsingen": "BL",
  "Lurtigen": "FR",
  "Lüscherz": "BE",
  "Lussery-Villars": "VD",
  "Lüsslingen": "SO",
  "Lussy FR": "FR",
  "Lussy-sur-Morges": "VD",
  "Lustdorf": "TG",
  "Lustmühle": "AR",
  "Luterbach": "SO",
  "Lüterkofen": "SO",
  "Lüterswil": "SO",
  "Luthern": "LU",
  "Luthern Bad": "LU",
  "Lütisburg": "SG",
  "Lütisburg Station": "SG",
  "Lutry": "VD",
  "Lütschental": "BE",
  "Lützelflüh-Goldbach": "BE",
  "Lutzenberg": "AR",
  "Luven": "GR",
  "Luzein": "GR",
  "Luzern": "LU",
  "Lyss": "BE",
  "Lyssach": "BE",
  "Mâche": "VS",
  "Madetswil": "ZH",
  "Madiswil": "BE",
  "Madonna del Piano": "TI",
  "Madrano": "TI",
  "Mädris-Vermol": "SG",
  "Madulain": "GR",
  "Magadino": "TI",
  "Magden": "AG",
  "Mägenwil": "AG",
  "Maggia": "TI",
  "Magglingen/Macolin": "BE",
  "Magliaso": "TI",
  "Maglio di Colla": "TI",
  "Magnedens": "FR",
  "Maienfeld": "GR",
  "Mairengo": "TI",
  "Maisprach": "BL",
  "Maladers": "GR",
  "Malans GR": "GR",
  "Malans SG": "SG",
  "Malix": "GR",
  "Malleray": "BE",
  "Maloja": "GR",
  "Malters": "LU",
  "Malvaglia": "TI",
  "Mamishaus": "BE",
  "Mammern": "TG",
  "Mandach": "AG",
  "Männedorf": "ZH",
  "Mannenbach-Salenstein": "TG",
  "Mannens": "FR",
  "Manno": "TI",
  "Maracon": "VD",
  "Marbach LU": "LU",
  "Marbach SG": "SG",
  "Marchissy": "VD",
  "Mariastein": "SO",
  "Marin-Epagnier": "NE",
  "Marly": "FR",
  "Marmorera": "GR",
  "Marnand": "VD",
  "Maroggia": "TI",
  "Marolta": "TI",
  "Marsens": "FR",
  "Märstetten": "TG",
  "Marthalen": "ZH",
  "Martherenges": "VD",
  "Martigny": "VS",
  "Martigny-Croix": "VS",
  "Martina": "GR",
  "Martisberg": "VS",
  "Märwil": "TG",
  "Maschwanden": "ZH",
  "Mase": "VS",
  "Masein": "GR",
  "Massagno": "TI",
  "Massongex": "VS",
  "Massonnens": "FR",
  "Mastrils": "GR",
  "Mathod": "VD",
  "Mathon": "GR",
  "Matran": "FR",
  "Matt": "GL",
  "Matten (St. Stephan)": "BE",
  "Matten b. Interlaken": "BE",
  "Mattstetten": "BE",
  "Mattwil": "TG",
  "Matzendorf": "SO",
  "Matzingen": "TG",
  "Mauborget": "VD",
  "Mauensee": "LU",
  "Maules": "FR",
  "Maur": "ZH",
  "Mauraz": "VD",
  "Mauren FL": "FL",
  "Mauren TG": "TG",
  "Mayens-de-Chamoson": "VS",
  "Mayens-de-la-Zour (Savièse)": "VS",
  "Medeglia": "TI",
  "Medels im Rheinwald": "GR",
  "Meggen": "LU",
  "Mehlsecken": "LU",
  "Meien": "UR",
  "Meienberg": "AG",
  "Meienried": "BE",
  "Meierskappel": "LU",
  "Meikirch": "BE",
  "Meilen": "ZH",
  "Meinier": "GE",
  "Meinisberg": "BE",
  "Meiringen": "BE",
  "Meisterschwanden": "AG",
  "Melano": "TI",
  "Melchsee-Frutt": "OW",
  "Melchtal": "OW",
  "Melide": "TI",
  "Mellingen": "AG",
  "Mels": "SG",
  "Meltingen": "SO",
  "Mendrisio": "TI",
  "Ménières": "FR",
  "Menzberg": "LU",
  "Menzengrüt": "ZH",
  "Menziken": "AG",
  "Menzingen": "ZG",
  "Menznau": "LU",
  "Menzonio": "TI",
  "Merenschwand": "AG",
  "Mergoscia": "TI",
  "Meride": "TI",
  "Merishausen": "SH",
  "Merligen": "BE",
  "Merlischachen": "SZ",
  "Mervelier": "JU",
  "Merzligen": "BE",
  "Mesocco": "GR",
  "Messen": "SO",
  "Mettau": "AG",
  "Mettembert": "JU",
  "Mettendorf TG": "TG",
  "Mettlen": "TG",
  "Mettmenstetten": "ZH",
  "Metzerlen": "SO",
  "Mex VD": "VD",
  "Mex VS": "VS",
  "Meyriez": "FR",
  "Meyrin": "GE",
  "Mézery-près-Donneloye": "VD",
  "Mézières FR": "FR",
  "Mézières VD": "VD",
  "Mezzovico": "TI",
  "Middes": "FR",
  "Miécourt": "JU",
  "Miège": "VS",
  "Mies": "VD",
  "Miex": "VS",
  "Miglieglia": "TI",
  "Milken": "BE",
  "Minusio": "TI",
  "Miralago": "GR",
  "Mirchel": "BE",
  "Misériez (Salins)": "VS",
  "Misery": "FR",
  "Missy": "VD",
  "Mitlödi": "GL",
  "Mittelhäusern": "BE",
  "Mittellunden": "GR",
  "Mogelsberg": "SG",
  "Moghegno": "TI",
  "Möhlin": "AG",
  "Moiry VD": "VD",
  "Molare": "TI",
  "Moleno": "TI",
  "Moléson-sur-Gruyères": "FR",
  "Molinazzo di Monteggio": "TI",
  "Molinis": "GR",
  "Mollens VD": "VD",
  "Mollens VS": "VS",
  "Mollie-Margot": "VD",
  "Mollis": "GL",
  "Molondin": "VD",
  "Mols": "SG",
  "Mompé Medel": "GR",
  "Mon": "GR",
  "Mönchaltorf": "ZH",
  "Moneto": "TI",
  "Monible": "BE",
  "Monnaz": "VD",
  "Mont-Crosin": "BE",
  "Mont-de-Buttes": "NE",
  "Mont-la-Ville": "VD",
  "Mont-Soleil": "BE",
  "Mont-sur-Rolle": "VD",
  "Mont-Tramelan": "BE",
  "Montagne-de-Courtelary": "BE",
  "Montagne-de-Sonvilier": "BE",
  "Montagnier (Le Châble VS)": "VS",
  "Montagnola": "TI",
  "Montagnon (Leytron)": "VS",
  "Montagny-la-Ville": "FR",
  "Montagny-les-Monts": "FR",
  "Montagny-près-Yverdon": "VD",
  "Montalchez": "NE",
  "Montana": "VS",
  "Montaubion-Chardonney": "VD",
  "Montavon": "JU",
  "Montbovon": "FR",
  "Montbrelloz": "FR",
  "Montcherand": "VD",
  "Monte": "TI",
  "Monte Brè sopra Locarno": "TI",
  "Monte Carasso": "TI",
  "Monteiller-Savièse": "VS",
  "Montenol": "JU",
  "Montet (Broye)": "FR",
  "Montet (Glâne)": "FR",
  "Montévraz": "FR",
  "Montezillon": "NE",
  "Montfaucon": "JU",
  "Montfavergier": "JU",
  "Mönthal": "AG",
  "Montherod": "VD",
  "Monthey": "VS",
  "Montignez": "JU",
  "Montlingen": "SG",
  "Montmagny": "VD",
  "Montmelon": "JU",
  "Montmollin": "NE",
  "Montpreveyres": "VD",
  "Montreux": "VD",
  "Montricher": "VD",
  "Montsevelier": "JU",
  "Moosleerau": "AG",
  "Moosseedorf": "BE",
  "Morbio Inferiore": "TI",
  "Morbio Superiore": "TI",
  "Morcles": "VD",
  "Morcote": "TI",
  "Mörel": "VS",
  "Morens FR": "FR",
  "Morgarten": "ZG",
  "Morges": "VD",
  "Morgins": "VS",
  "Mörigen": "BE",
  "Möriken AG": "AG",
  "Morissen": "GR",
  "Morlens": "FR",
  "Morlon": "FR",
  "Morrens VD": "VD",
  "Morschach": "SZ",
  "Mörschwil": "SG",
  "Mosen": "LU",
  "Mosogno": "TI",
  "Mossel": "FR",
  "Môtier (Vully)": "FR",
  "Môtiers NE": "NE",
  "Mötschwil": "BE",
  "Motto (Blenio)": "TI",
  "Moudon": "VD",
  "Moutier": "BE",
  "Movelier": "JU",
  "Mugena": "TI",
  "Muggio": "TI",
  "Muhen": "AG",
  "Mühlau": "AG",
  "Mühlebach (Goms)": "VS",
  "Mühleberg": "BE",
  "Mühledorf BE": "BE",
  "Mühledorf SO": "SO",
  "Mühlehorn": "GL",
  "Mühlethal": "AG",
  "Mühlethurnen": "BE",
  "Mülchi": "BE",
  "Mulegns": "GR",
  "Mülenen": "BE",
  "Müllheim Dorf": "TG",
  "Müllheim-Wigoltingen": "TG",
  "Mülligen": "AG",
  "Mümliswil": "SO",
  "Mumpf": "AG",
  "Münchenbuchsee": "BE",
  "Münchenstein": "BL",
  "Münchenwiler": "BE",
  "Münchringen": "BE",
  "Münchwilen AG": "AG",
  "Münchwilen TG": "TG",
  "Mund": "VS",
  "Münsingen": "BE",
  "Münster VS": "VS",
  "Münsterlingen": "TG",
  "Muntelier": "FR",
  "Müntschemier": "BE",
  "Muolen": "SG",
  "Muotathal": "SZ",
  "Mur (Vully) FR": "FR",
  "Mur (Vully) VD": "VD",
  "Muralto": "TI",
  "Muraz (Collombey)": "VS",
  "Muraz (Sierre)": "VS",
  "Murg": "SG",
  "Murgenthal": "AG",
  "Muri AG": "AG",
  "Muri b. Bern": "BE",
  "Muriaux": "JU",
  "Murist": "FR",
  "Mürren": "BE",
  "Murten": "FR",
  "Murzelen": "BE",
  "Müselbach": "SG",
  "Müstair": "GR",
  "Müswangen": "LU",
  "Mutrux": "VD",
  "Mutten": "GR",
  "Muttenz": "BL",
  "Muzzano": "TI",
  "Näfels": "GL",
  "Nänikon": "ZH",
  "Nassen": "SG",
  "Naters": "VS",
  "Nax": "VS",
  "Naz": "VD",
  "Nebikon": "LU",
  "Necker": "SG",
  "Neerach": "ZH",
  "Neftenbach": "ZH",
  "Neggio": "TI",
  "Neirivue": "FR",
  "Némiaz (Chamoson)": "VS",
  "Nendeln": "FL",
  "Nennigkofen": "SO",
  "Nenzlingen": "BL",
  "Neschwil": "ZH",
  "Nesselnbach": "AG",
  "Netstal": "GL",
  "Neuägeri": "ZG",
  "Neuchâtel": "NE",
  "Neudorf": "LU",
  "Neuendorf": "SO",
  "Neuenegg": "BE",
  "Neuenhof": "AG",
  "Neuenkirch": "LU",
  "Neuhaus SG": "SG",
  "Neuhausen am Rheinfall": "SH",
  "Neuheim": "ZG",
  "Neukirch (Egnach)": "TG",
  "Neukirch an der Thur": "TG",
  "Neunkirch": "SH",
  "Neuwilen": "TG",
  "Neyruz FR": "FR",
  "Neyruz-sur-Moudon": "VD",
  "Nidau": "BE",
  "Nidfurn": "GL",
  "Niederbipp": "BE",
  "Niederbuchsiten": "SO",
  "Niederbüren": "SG",
  "Niederdorf": "BL",
  "Niedergampel": "VS",
  "Niedergesteln": "VS",
  "Niederglatt SG": "SG",
  "Niederglatt ZH": "ZH",
  "Niedergösgen": "SO",
  "Niederhasli": "ZH",
  "Niederhelfenschwil": "SG",
  "Niederhünigen": "BE",
  "Niederlenz": "AG",
  "Niedermuhlern": "BE",
  "Niederneunforn": "TG",
  "Niederönz": "BE",
  "Niederösch": "BE",
  "Niederrickenbach": "NW",
  "Niederried b. Interlaken": "BE",
  "Niederried b. Kallnach": "BE",
  "Niederrohrdorf": "AG",
  "Niederscherli": "BE",
  "Niederstetten": "SG",
  "Niederstocken": "BE",
  "Niederteufen": "AR",
  "Niederurnen": "GL",
  "Niederuzwil": "SG",
  "Niederwald": "VS",
  "Niederwangen b. Bern": "BE",
  "Niederweningen": "ZH",
  "Niederwil AG": "AG",
  "Niederwil SG": "SG",
  "Niederwil SO": "SO",
  "Nierlet-les-Bois": "FR",
  "Niouc": "VS",
  "Niva (Vallemaggia)": "TI",
  "Nivo": "TI",
  "Nods": "BE",
  "Noës": "VS",
  "Noflen BE": "BE",
  "Nohl": "ZH",
  "Noiraigue": "NE",
  "Noréaz": "FR",
  "Nottwil": "LU",
  "Novaggio": "TI",
  "Novalles": "VD",
  "Novazzano": "TI",
  "Noville": "VD",
  "Nufenen": "GR",
  "Nuglar": "SO",
  "Nunningen": "SO",
  "Nürensdorf": "ZH",
  "Nussbaumen AG": "AG",
  "Nussbaumen TG": "TG",
  "Nusshof": "BL",
  "Nuvilly": "FR",
  "Nyon": "VD",
  "Obbürgen": "NW",
  "Oberaach": "TG",
  "Oberägeri": "ZG",
  "Oberarth": "SZ",
  "Oberbalm": "BE",
  "Oberbalmberg": "SO",
  "Oberbipp": "BE",
  "Oberbözberg": "AG",
  "Oberbuchsiten": "SO",
  "Oberbüren": "SG",
  "Oberburg": "BE",
  "Oberbussnang": "TG",
  "Oberbütschel": "BE",
  "Oberdiessbach": "BE",
  "Oberdorf BL": "BL",
  "Oberdorf NW": "NW",
  "Oberdorf SO": "SO",
  "Oberegg": "AI",
  "Oberembrach": "ZH",
  "Oberems": "VS",
  "Oberengstringen": "ZH",
  "Oberentfelden": "AG",
  "Oberflachs": "AG",
  "Oberfrittenbach": "BE",
  "Obergerlafingen": "SO",
  "Obergesteln": "VS",
  "Obergoldbach": "BE",
  "Obergösgen": "SO",
  "Oberhallau": "SH",
  "Oberhasli": "ZH",
  "Oberhof": "AG",
  "Oberhofen AG": "AG",
  "Oberhofen am Thunersee": "BE",
  "Oberhünigen": "BE",
  "Oberiberg": "SZ",
  "Oberkirch LU": "LU",
  "Oberkulm": "AG",
  "Oberlunkhofen": "AG",
  "Obermumpf": "AG",
  "Obermutten": "GR",
  "Obernau": "LU",
  "Oberneunforn": "TG",
  "Oberönz": "BE",
  "Oberösch": "BE",
  "Oberramsern": "SO",
  "Oberrickenbach": "NW",
  "Oberried am Brienzersee": "BE",
  "Oberried FR": "FR",
  "Oberrieden": "ZH",
  "Oberriet SG": "SG",
  "Oberrohrdorf": "AG",
  "Oberrüti": "AG",
  "Obersaxen Affeier": "GR",
  "Obersaxen Friggahüs": "GR",
  "Obersaxen Giraniga": "GR",
  "Obersaxen Meierhof": "GR",
  "Oberschan": "SG",
  "Oberschrot": "FR",
  "Oberstammheim": "ZH",
  "Obersteckholz": "BE",
  "Oberstetten": "SG",
  "Oberstocken": "BE",
  "Oberterzen": "SG",
  "Oberthal": "BE",
  "Oberurnen": "GL",
  "Oberuzwil": "SG",
  "Oberwald": "VS",
  "Oberwangen b. Bern": "BE",
  "Oberwangen TG": "TG",
  "Oberweningen": "ZH",
  "Oberwil (Dägerlen)": "ZH",
  "Oberwil b. Büren": "BE",
  "Oberwil b. Zug": "ZG",
  "Oberwil BL": "BL",
  "Oberwil im Simmental": "BE",
  "Oberwil-Lieli": "AG",
  "Obfelden": "ZH",
  "Obstalden": "GL",
  "Ochlenberg": "BE",
  "Ocourt": "JU",
  "Odogno": "TI",
  "Oekingen": "SO",
  "Oensingen": "SO",
  "Oerlingen": "ZH",
  "Oeschenbach": "BE",
  "Oeschgen": "AG",
  "Oeschseite": "BE",
  "Oetwil am See": "ZH",
  "Oetwil an der Limmat": "ZH",
  "Oey": "BE",
  "Oftringen": "AG",
  "Ogens": "VD",
  "Oggio": "TI",
  "Ohmstal": "LU",
  "Oleyres": "VD",
  "Olivone": "TI",
  "Ollon VD": "VD",
  "Ollon VS": "VS",
  "Olsberg": "AG",
  "Olten": "SO",
  "Oltingen": "BL",
  "Onex": "GE",
  "Onnens FR": "FR",
  "Onnens VD": "VD",
  "Opfershofen TG": "TG",
  "Opfertshofen SH": "SH",
  "Opfikon": "ZH",
  "Oppens": "VD",
  "Oppikon": "TG",
  "Oppligen": "BE",
  "Orbe": "VD",
  "Orges": "VD",
  "Orient": "VD",
  "Origlio": "TI",
  "Ormalingen": "BL",
  "Ormône (Savièse)": "VS",
  "Orny": "VD",
  "Oron-la-Ville": "VD",
  "Oron-le-Châtel": "VD",
  "Orpund": "BE",
  "Orselina": "TI",
  "Orsières": "VS",
  "Orsonnens": "FR",
  "Ortschwaben": "BE",
  "Orvin": "BE",
  "Orzens": "VD",
  "Oschwand": "BE",
  "Osco": "TI",
  "Osogna": "TI",
  "Ospizio Bernina": "GR",
  "Ossingen": "ZH",
  "Osterfingen": "SH",
  "Ostermundigen": "BE",
  "Otelfingen": "ZH",
  "Othmarsingen": "AG",
  "Ottenbach": "ZH",
  "Ottikon (Gossau ZH)": "ZH",
  "Ottikon b. Kemptthal": "ZH",
  "Ottoberg": "TG",
  "Oulens-sous-Echallens": "VD",
  "Oulens-sur-Lucens": "VD",
  "Ovronnaz": "VS",
  "Pagig": "GR",
  "Pailly": "VD",
  "Palagnedra": "TI",
  "Palasuit (Liddes)": "VS",
  "Palézieux": "VD",
  "Palézieux-Village": "VD",
  "Pambio-Noranco": "TI",
  "Pampigny": "VD",
  "Panex": "VD",
  "Pany": "GR",
  "Paradiso": "TI",
  "Parpan": "GR",
  "Parsonz": "GR",
  "Paspels": "GR",
  "Passugg-Araschgen": "GR",
  "Paudex": "VD",
  "Payerne": "VD",
  "Pazzallo": "TI",
  "Peccia": "TI",
  "Pedrinate": "TI",
  "Peiden": "GR",
  "Peist": "GR",
  "Peney-le-Jorat": "VD",
  "Pensier": "FR",
  "Penthalaz": "VD",
  "Penthaz": "VD",
  "Penthéréaz": "VD",
  "Perlen": "LU",
  "Perly": "GE",
  "Perrefitte": "BE",
  "Perroy": "VD",
  "Personico": "TI",
  "Péry": "BE",
  "Peseux": "NE",
  "Petit Vichères (Liddes)": "VS",
  "Petit-Lancy": "GE",
  "Petit-Martel": "NE",
  "Peyres-Possens": "VD",
  "Pfäfers": "SG",
  "Pfaffhausen": "ZH",
  "Pfäffikon SZ": "SZ",
  "Pfäffikon ZH": "ZH",
  "Pfaffnau": "LU",
  "Pfeffikon LU": "LU",
  "Pfeffingen": "BL",
  "Pfungen": "ZH",
  "Pfyn": "TG",
  "Piandera Paese": "TI",
  "Pianezzo": "TI",
  "Piano di Peccia": "TI",
  "Piazzogna": "TI",
  "Pierrafortscha": "FR",
  "Pieterlen": "BE",
  "Pignia": "GR",
  "Pigniu": "GR",
  "Pilatus Kulm": "OW",
  "Piotta": "TI",
  "Pitasch": "GR",
  "Pizy": "VD",
  "Plaffeien": "FR",
  "Plagne": "BE",
  "Plan-les-Ouates": "GE",
  "Planken": "FL",
  "Plasselb": "FR",
  "Platta": "GR",
  "Plaun da Lej": "GR",
  "Pleigne": "JU",
  "Pleujouse": "JU",
  "Plons": "SG",
  "Pohlern": "BE",
  "Poliez-le-Grand": "VD",
  "Poliez-Pittet": "VD",
  "Pollegio": "TI",
  "Pompaples": "VD",
  "Pomy": "VD",
  "Pont (Veveyse)": "FR",
  "Pont-de-la-Morge (Sion)": "VS",
  "Pont-la-Ville": "FR",
  "Ponte Capriasca": "TI",
  "Ponte Cremenaga": "TI",
  "Ponte Tresa": "TI",
  "Pontenet": "BE",
  "Ponthaux": "FR",
  "Ponto Valentino": "TI",
  "Pontresina": "GR",
  "Porrentruy": "JU",
  "Porsel": "FR",
  "Port": "BE",
  "Portalban": "FR",
  "Portein": "GR",
  "Porto Ronco": "TI",
  "Porza": "TI",
  "Posat": "FR",
  "Poschiavo": "GR",
  "Posieux": "FR",
  "Praden": "GR",
  "Pragg-Jenaz": "GR",
  "Prahins": "VD",
  "Prangins": "VD",
  "Praratoud": "FR",
  "Prarreyer (Versegères)": "VS",
  "Prato (Leventina)": "TI",
  "Prato-Sornico": "TI",
  "Pratteln": "BL",
  "Pratval": "GR",
  "Pravidondaz (Salins)": "VS",
  "Präz": "GR",
  "Praz (Vully)": "FR",
  "Praz-de-Fort": "VS",
  "Preda": "GR",
  "Pregassona": "TI",
  "Prêles": "BE",
  "Premier": "VD",
  "Preonzo": "TI",
  "Presinge": "GE",
  "Préverenges": "VD",
  "Prévondavaux": "FR",
  "Prévonloup": "VD",
  "Prez-vers-Noréaz": "FR",
  "Prez-vers-Siviriez": "FR",
  "Prilly": "VD",
  "Pringy": "FR",
  "Produit (Leytron)": "VS",
  "Progens": "FR",
  "Promasens": "FR",
  "Promontogno": "GR",
  "Prosito": "TI",
  "Provence": "VD",
  "Prugiasco": "TI",
  "Pugerna": "TI",
  "Puidoux": "VD",
  "Pully": "VD",
  "Puplinge": "GE",
  "Pura": "TI",
  "Purasca": "TI",
  "Pusserein": "GR",
  "Putz": "GR",
  "Quarten": "SG",
  "Quartino": "TI",
  "Quinten": "SG",
  "Quinto": "TI",
  "Rabius": "GR",
  "Radelfingen b. Aarberg": "BE",
  "Rafz": "ZH",
  "Rain": "LU",
  "Ramersberg": "OW",
  "Rämismühle": "ZH",
  "Ramiswil": "SO",
  "Ramlinsburg": "BL",
  "Ramosch": "GR",
  "Ramsei": "BE",
  "Ramsen": "SH",
  "Rancate": "TI",
  "Rances": "VD",
  "Randa": "VS",
  "Randogne": "VS",
  "Ranflüh": "BE",
  "Ranzo": "TI",
  "Raperswilen": "TG",
  "Rapperswil BE": "BE",
  "Rapperswil SG": "SG",
  "Raron": "VS",
  "Rasa": "TI",
  "Ravoire": "VS",
  "Realp": "UR",
  "Realta": "GR",
  "Rebeuvelier": "JU",
  "Rebévelier": "BE",
  "Rebstein": "SG",
  "Recherswil": "SO",
  "Rechthalten": "FR",
  "Réchy": "VS",
  "Reckingen VS": "VS",
  "Réclère": "JU",
  "Reconvilier": "BE",
  "Regensberg": "ZH",
  "Regensdorf": "ZH",
  "Rehetobel": "AR",
  "Reichenbach im Kandertal": "BE",
  "Reichenburg": "SZ",
  "Reiden": "LU",
  "Reidermoos": "LU",
  "Reigoldswil": "BL",
  "Reinach AG": "AG",
  "Reinach BL": "BL",
  "Reisiswil": "BE",
  "Reitnau": "AG",
  "Rekingen AG": "AG",
  "Remaufens": "FR",
  "Remetschwil": "AG",
  "Remigen": "AG",
  "Renan BE": "BE",
  "Renens VD": "VD",
  "Rengg": "LU",
  "Rennaz": "VD",
  "Retschwil": "LU",
  "Reute AR": "AR",
  "Reutigen": "BE",
  "Reutlingen (Winterthur)": "ZH",
  "Reverolle": "VD",
  "Rhäzüns": "GR",
  "Rheinau": "ZH",
  "Rheineck": "SG",
  "Rheinfelden": "AG",
  "Rheinklingen": "TG",
  "Rheinsulz": "AG",
  "Riaz": "FR",
  "Riazzino": "TI",
  "Richenthal": "LU",
  "Richigen": "BE",
  "Richterswil": "ZH",
  "Ricken SG": "SG",
  "Rickenbach b. Schwyz": "SZ",
  "Rickenbach b. Wil": "TG",
  "Rickenbach BL": "BL",
  "Rickenbach LU": "LU",
  "Rickenbach SO": "SO",
  "Rickenbach Sulz": "ZH",
  "Rickenbach ZH": "ZH",
  "Ricketwil (Winterthur)": "ZH",
  "Riddes": "VS",
  "Ried (Frutigen)": "BE",
  "Ried (Muotathal)": "SZ",
  "Ried b. Kerzers": "FR",
  "Ried-Brig": "VS",
  "Ried-Mörel": "VS",
  "Rieden AG": "AG",
  "Rieden SG": "SG",
  "Riederalp": "VS",
  "Riedern": "GL",
  "Riedholz": "SO",
  "Riedikon": "ZH",
  "Riedstätt": "BE",
  "Riedt b. Erlen": "TG",
  "Riedtwil": "BE",
  "Riehen": "BS",
  "Riein": "GR",
  "Riemenstalden": "SZ",
  "Riet (Neftenbach)": "ZH",
  "Rietheim": "AG",
  "Riex": "VD",
  "Riffenmatt": "BE",
  "Rifferswil": "ZH",
  "Riggisberg": "BE",
  "Rigi Kaltbad": "LU",
  "Rigi Klösterli": "SZ",
  "Rigi Kulm": "SZ",
  "Rigi Scheidegg": "SZ",
  "Rigi Staffel": "SZ",
  "Riken AG": "AG",
  "Rikon im Tösstal": "ZH",
  "Ringgenberg BE": "BE",
  "Ringoldswil": "BE",
  "Riniken": "AG",
  "Riom": "GR",
  "Risch": "ZG",
  "Ritzingen": "VS",
  "Riva San Vitale": "TI",
  "Rivaz": "VD",
  "Rive Haute (Liddes)": "VS",
  "Riveo": "TI",
  "Rivera": "TI",
  "Rizenbach": "BE",
  "Robasacco": "TI",
  "Roche VD": "VD",
  "Roche-d'Or": "JU",
  "Rochefort": "NE",
  "Roches BE": "BE",
  "Rocourt": "JU",
  "Rodels": "GR",
  "Rodersdorf": "SO",
  "Rodi-Fiesso": "TI",
  "Roggenburg": "BL",
  "Roggliswil": "LU",
  "Roggwil BE": "BE",
  "Roggwil TG": "TG",
  "Rohr b. Olten": "SO",
  "Rohrbach": "BE",
  "Rohrbachgraben": "BE",
  "Rohrmatt": "LU",
  "Rolle": "VD",
  "Romainmôtier": "VD",
  "Romairon": "VD",
  "Romanel-sur-Lausanne": "VD",
  "Romanel-sur-Morges": "VD",
  "Romanens": "FR",
  "Romanshorn": "TG",
  "Rombach": "AG",
  "Römerswil LU": "LU",
  "Romont BE": "BE",
  "Romont FR": "FR",
  "Romoos": "LU",
  "Rona": "GR",
  "Ronco sopra Ascona": "TI",
  "Rongellen": "GR",
  "Root": "LU",
  "Root Längenbold": "LU",
  "Ropraz": "VD",
  "Rorbas": "ZH",
  "Rorschach": "SG",
  "Rorschacherberg": "SG",
  "Röschenz": "BL",
  "Rosé": "FR",
  "Rosenlaui": "BE",
  "Rossa": "GR",
  "Rossemaison": "JU",
  "Rossenges": "VD",
  "Rossens FR": "FR",
  "Rossens VD": "VD",
  "Rosshäusern": "BE",
  "Rossinière": "VD",
  "Rossrüti": "SG",
  "Rossura": "TI",
  "Rosswald": "VS",
  "Röthenbach Herzogenbuchsee": "BE",
  "Röthenbach im Emmental": "BE",
  "Rothenbrunnen": "GR",
  "Rothenburg": "LU",
  "Rothenfluh": "BL",
  "Rothenhausen": "TG",
  "Rothenthurm": "SZ",
  "Rothrist": "AG",
  "Rothwald": "VS",
  "Rotkreuz": "ZG",
  "Rottenschwil": "AG",
  "Rougemont": "VD",
  "Roumaz (Savièse)": "VS",
  "Roveredo GR": "GR",
  "Roveredo TI": "TI",
  "Rovio": "TI",
  "Rovray": "VD",
  "Rubigen": "BE",
  "Rüderswil": "BE",
  "Rüdlingen": "SH",
  "Rudolfingen": "ZH",
  "Rudolfstetten": "AG",
  "Rüdtligen": "BE",
  "Rue": "FR",
  "Rüedisbach": "BE",
  "Rüeggisberg": "BE",
  "Rüegsau": "BE",
  "Rüegsauschachen": "BE",
  "Rüegsbach": "BE",
  "Rueras": "GR",
  "Rüeterswil": "SG",
  "Rueun": "GR",
  "Rueyres": "VD",
  "Rueyres-les-Prés": "FR",
  "Rueyres-St-Laurent": "FR",
  "Rueyres-Treyfayes": "FR",
  "Rüfenach AG": "AG",
  "Rüfenacht BE": "BE",
  "Rufi": "SG",
  "Ruggell": "FL",
  "Rumendingen": "BE",
  "Rümikon AG": "AG",
  "Rumisberg": "BE",
  "Rümlang": "ZH",
  "Rümligen": "BE",
  "Rümlingen": "BL",
  "Rünenberg": "BL",
  "Rupperswil": "AG",
  "Ruppoldsried": "BE",
  "Rüschegg Gambach": "BE",
  "Rüschegg Heubach": "BE",
  "Ruschein": "GR",
  "Rüschlikon": "ZH",
  "Russikon": "ZH",
  "Russin": "GE",
  "Russo": "TI",
  "Russy": "FR",
  "Ruswil": "LU",
  "Rüthi (Rheintal)": "SG",
  "Rüti b. Büren": "BE",
  "Rüti b. Lyssach": "BE",
  "Rüti b. Riggisberg": "BE",
  "Rüti GL": "GL",
  "Rüti ZH": "ZH",
  "Rütihof": "AG",
  "Rütli": "UR",
  "Rütschelen": "BE",
  "Rutschwil (Dägerlen)": "ZH",
  "Rüttenen": "SO",
  "Ruvigliana": "TI",
  "S-chanf": "GR",
  "S. Antonino": "TI",
  "S. Antonio (Val Morobbia)": "TI",
  "S. Benedetg": "GR",
  "S. Bernardino": "GR",
  "S. Carlo (Poschiavo)": "GR",
  "S. Carlo (Val Bavona)": "TI",
  "S. Nazzaro": "TI",
  "S. Pietro": "TI",
  "S. Vittore": "GR",
  "Saanen": "BE",
  "Saanenmöser": "BE",
  "Saas im Prättigau": "GR",
  "Saas-Almagell": "VS",
  "Saas-Balen": "VS",
  "Saas-Fee": "VS",
  "Saas-Grund": "VS",
  "Sachseln": "OW",
  "Saclentz (Nendaz)": "VS",
  "Safenwil": "AG",
  "Safien Platz": "GR",
  "Safnern": "BE",
  "Sagno": "TI",
  "Sagogn": "GR",
  "Saicourt": "BE",
  "Saignelégier": "JU",
  "Saillon": "VS",
  "Sala Capriasca": "TI",
  "Saland": "ZH",
  "Salavaux": "VD",
  "Salenstein": "TG",
  "Sâles (Gruyère)": "FR",
  "Salez": "SG",
  "Salgesch": "VS",
  "Salins": "VS",
  "Salmsach": "TG",
  "Salorino": "TI",
  "Salouf": "GR",
  "Salvan": "VS",
  "Salvenach": "FR",
  "Samedan": "GR",
  "Samnaun Dorf": "GR",
  "Samnaun-Compatsch": "GR",
  "Samstagern": "ZH",
  "Sangernboden": "BE",
  "Sargans": "SG",
  "Säriswil": "BE",
  "Sarmenstorf": "AG",
  "Sarn": "GR",
  "Sarnen": "OW",
  "Sarreyer": "VS",
  "Sarzens": "VD",
  "Sassel": "VD",
  "Satigny": "GE",
  "Sattel": "SZ",
  "Saubraz": "VD",
  "Saulcy": "JU",
  "Saules": "NE",
  "Saules BE": "BE",
  "Savagnier": "NE",
  "Savièse": "VS",
  "Savigny": "VD",
  "Savognin": "GR",
  "Savosa": "TI",
  "Sax": "SG",
  "Saxeten": "BE",
  "Saxon": "VS",
  "Saxonne (Ayent)": "VS",
  "Says": "GR",
  "Scareglia": "TI",
  "Schaan": "FL",
  "Schaanwald": "FL",
  "Schachen b. Herisau": "AR",
  "Schachen b. Reute": "AR",
  "Schachen LU": "LU",
  "Schaffhausen": "SH",
  "Schafhausen im Emmental": "BE",
  "Schafisheim": "AG",
  "Schalunen": "BE",
  "Schangnau": "BE",
  "Schänis": "SG",
  "Scharans": "GR",
  "Scharnachtal": "BE",
  "Schattdorf": "UR",
  "Schattenhalb": "BE",
  "Scheid": "GR",
  "Schellenberg": "FL",
  "Schelten": "BE",
  "Schenkon": "LU",
  "Scherz": "AG",
  "Scherzingen": "TG",
  "Scheunen": "BE",
  "Scheuren": "BE",
  "Schiers": "GR",
  "Schinznach Bad": "AG",
  "Schinznach Dorf": "AG",
  "Schlans": "GR",
  "Schlatt b. Winterthur": "ZH",
  "Schlatt TG": "TG",
  "Schlattingen": "TG",
  "Schleinikon": "ZH",
  "Schleitheim": "SH",
  "Schlierbach": "LU",
  "Schlieren": "ZH",
  "Schliern b. Köniz": "BE",
  "Schlossrued": "AG",
  "Schlosswil": "BE",
  "Schluein": "GR",
  "Schmerikon": "SG",
  "Schmidigen-Mühleweg": "BE",
  "Schmidrüti": "ZH",
  "Schmidshof": "TG",
  "Schmiedrued": "AG",
  "Schmiedrued-Walde": "AG",
  "Schmitten (Albula)": "GR",
  "Schmitten FR": "FR",
  "Schnaus": "GR",
  "Schneisingen": "AG",
  "Schnottwil": "SO",
  "Schocherswil": "TG",
  "Schöfflisdorf": "ZH",
  "Schöftland": "AG",
  "Schönenbaumgarten": "TG",
  "Schönenberg an der Thur": "TG",
  "Schönenberg ZH": "ZH",
  "Schönenbuch": "BL",
  "Schönengrund": "AR",
  "Schönenwerd": "SO",
  "Schongau": "LU",
  "Schönholzerswilen": "TG",
  "Schönried": "BE",
  "Schötz": "LU",
  "Schübelbach": "SZ",
  "Schuders": "GR",
  "Schüpbach": "BE",
  "Schupfart": "AG",
  "Schüpfen": "BE",
  "Schüpfheim": "LU",
  "Schwaderloch": "AG",
  "Schwadernau": "BE",
  "Schwanden (Sigriswil)": "BE",
  "Schwanden b. Brienz": "BE",
  "Schwanden GL": "GL",
  "Schwanden im Emmental": "BE",
  "Schwändi b. Schwanden": "GL",
  "Schwarzenbach (Huttwil)": "BE",
  "Schwarzenbach Beromünster": "LU",
  "Schwarzenbach SG": "SG",
  "Schwarzenberg LU": "LU",
  "Schwarzenburg": "BE",
  "Schwarzenegg": "BE",
  "Schwarzhäusern": "BE",
  "Schwarzsee": "FR",
  "Schweizersholz": "TG",
  "Schwellbrunn": "AR",
  "Schwende": "AI",
  "Schwenden im Diemtigtal": "BE",
  "Schwendi im Weisstannental": "SG",
  "Schwendibach": "BE",
  "Schwerzenbach": "ZH",
  "Schwyz": "SZ",
  "Scudellate": "TI",
  "Scuol": "GR",
  "Sédeilles": "VD",
  "Sedrun": "GR",
  "Seeberg": "BE",
  "Seedorf BE": "BE",
  "Seedorf UR": "UR",
  "Seehof": "BE",
  "Seelisberg": "UR",
  "Seengen": "AG",
  "Seewen SO": "SO",
  "Seewen SZ": "SZ",
  "Seewil": "BE",
  "Seewis Dorf": "GR",
  "Seewis-Pardisla": "GR",
  "Seewis-Schmitten": "GR",
  "Seftigen": "BE",
  "Segnas": "GR",
  "Seigneux": "VD",
  "Seiry": "FR",
  "Seleute": "JU",
  "Selkingen": "VS",
  "Selma": "GR",
  "Seltisberg": "BL",
  "Selzach": "SO",
  "Sembrancher": "VS",
  "Sementina": "TI",
  "Semione": "TI",
  "Sempach": "LU",
  "Sempach Station": "LU",
  "Semsales": "FR",
  "Senarclens": "VD",
  "Senèdes": "FR",
  "Sennhof (Winterthur)": "ZH",
  "Sennwald": "SG",
  "Sent": "GR",
  "Seon": "AG",
  "Sergey": "VD",
  "Serneus": "GR",
  "Serpiano": "TI",
  "Servion": "VD",
  "Seseglio": "TI",
  "Sessa": "TI",
  "Seuzach": "ZH",
  "Sévaz": "FR",
  "Sevelen": "SG",
  "Sévery": "VD",
  "Sevgein": "GR",
  "Sfazù": "GR",
  "Siat": "GR",
  "Siblingen": "SH",
  "Siebnen": "SZ",
  "Siegershausen": "TG",
  "Sierre": "VS",
  "Siggenthal Station": "AG",
  "Sigigen": "LU",
  "Sigirino": "TI",
  "Siglistorf": "AG",
  "Signau": "BE",
  "Signèse (Ayent)": "VS",
  "Signôra": "TI",
  "Signy": "VD",
  "Sigriswil": "BE",
  "Sihlbrugg": "ZG",
  "Sihlbrugg Station": "ZH",
  "Sihlwald": "ZH",
  "Silenen": "UR",
  "Sils im Domleschg": "GR",
  "Sils/Segl Baselgia": "GR",
  "Sils/Segl Maria": "GR",
  "Silvaplana": "GR",
  "Silvaplana-Surlej": "GR",
  "Simplon Dorf": "VS",
  "Simplon Hospiz": "VS",
  "Sins": "AG",
  "Sion": "VS",
  "Sirnach": "TG",
  "Siselen BE": "BE",
  "Sisikon": "UR",
  "Sissach": "BL",
  "Sisseln AG": "AG",
  "Sitterdorf": "TG",
  "Siviez (Nendaz)": "VS",
  "Siviriez": "FR",
  "Soazza": "GR",
  "Sobrio": "TI",
  "Soglio": "GR",
  "Solduno": "TI",
  "Solothurn": "SO",
  "Somazzo": "TI",
  "Someo": "TI",
  "Sommentier": "FR",
  "Sommeri": "TG",
  "Sonceboz-Sombeval": "BE",
  "Sonnental": "SG",
  "Sonogno": "TI",
  "Sonterswil": "TG",
  "Sonvico": "TI",
  "Sonvilier": "BE",
  "Sool": "GL",
  "Soral": "GE",
  "Sörenberg": "LU",
  "Sorengo": "TI",
  "Sorens": "FR",
  "Sornetan": "BE",
  "Sorvilier": "BE",
  "Sottens": "VD",
  "Soubey": "JU",
  "Souboz": "BE",
  "Soulce": "JU",
  "Soyhières": "JU",
  "Speicher": "AR",
  "Speicherschwendi": "AR",
  "Spiegel b. Bern": "BE",
  "Spiez": "BE",
  "Spiringen": "UR",
  "Splügen": "GR",
  "Spreitenbach": "AG",
  "Spruga": "TI",
  "St-Aubin FR": "FR",
  "St-Aubin-Sauges": "NE",
  "St-Barthélemy VD": "VD",
  "St-Blaise": "NE",
  "St-Brais": "JU",
  "St-Cergue": "VD",
  "St-Cierges": "VD",
  "St-George": "VD",
  "St-Germain (Savièse)": "VS",
  "St-Gingolph": "VS",
  "St-Imier": "BE",
  "St-Jean VS": "VS",
  "St-Légier-La Chiésaz": "VD",
  "St-Léonard": "VS",
  "St-Livres": "VD",
  "St-Luc": "VS",
  "St-Martin FR": "FR",
  "St-Martin VS": "VS",
  "St-Maurice": "VS",
  "St-Oyens": "VD",
  "St-Pierre-de-Clages": "VS",
  "St-Prex": "VD",
  "St-Romain (Ayent)": "VS",
  "St-Saphorin (Lavaux)": "VD",
  "St-Saphorin-sur-Morges": "VD",
  "St-Séverin": "VS",
  "St-Sulpice NE": "NE",
  "St-Sulpice VD": "VD",
  "St-Triphon": "VD",
  "St-Ursanne": "JU",
  "St. Antoni": "FR",
  "St. Antönien": "GR",
  "St. Erhard": "LU",
  "St. Gallen": "SG",
  "St. Gallenkappel": "SG",
  "St. German": "VS",
  "St. Margarethen TG": "TG",
  "St. Margrethen SG": "SG",
  "St. Margrethenberg": "SG",
  "St. Martin (Lugnez)": "GR",
  "St. Moritz": "GR",
  "St. Niklaus VS": "VS",
  "St. Niklausen LU": "LU",
  "St. Niklausen OW": "OW",
  "St. Pantaleon": "SO",
  "St. Pelagiberg": "TG",
  "St. Peter": "GR",
  "St. Peterzell": "SG",
  "St. Silvester": "FR",
  "St. Stephan": "BE",
  "St. Urban": "LU",
  "St. Ursen": "FR",
  "Sta. Maria in Calanca": "GR",
  "Sta. Maria Val Müstair": "GR",
  "Staad SG": "SG",
  "Stabio": "TI",
  "Stachen": "TG",
  "Stadel (Winterthur)": "ZH",
  "Stadel b. Niederglatt": "ZH",
  "Stäfa": "ZH",
  "Staffelbach": "AG",
  "Stalden (Sarnen)": "OW",
  "Stalden VS": "VS",
  "Staldenried": "VS",
  "Stallikon": "ZH",
  "Stampa": "GR",
  "Stans": "NW",
  "Stansstad": "NW",
  "Starrkirch-Wil": "SO",
  "Staufen": "AG",
  "Ste-Croix": "VD",
  "Stechelberg": "BE",
  "Steckborn": "TG",
  "Steffisburg": "BE",
  "Steg im Tösstal": "ZH",
  "Steg VS": "VS",
  "Stehrenberg": "TG",
  "Stein AG": "AG",
  "Stein am Rhein": "SH",
  "Stein AR": "AR",
  "Steinach": "SG",
  "Steinebrunn": "TG",
  "Steinen": "SZ",
  "Steinerberg": "SZ",
  "Steinhaus": "VS",
  "Steinhausen": "ZG",
  "Steinhof SO": "SO",
  "Steinhuserberg": "LU",
  "Steinmaur": "ZH",
  "Stels": "GR",
  "Sternenberg": "ZH",
  "Stetten AG": "AG",
  "Stetten SH": "SH",
  "Stettfurt": "TG",
  "Stettlen": "BE",
  "Stierva": "GR",
  "Stilli": "AG",
  "Stoos SZ": "SZ",
  "Strada": "GR",
  "Strengelbach": "AG",
  "Studen BE": "BE",
  "Studen SZ": "SZ",
  "Stugl/Stuls": "GR",
  "Stüsslingen": "SO",
  "Suberg": "BE",
  "Subingen": "SO",
  "Suchy": "VD",
  "Süderen": "BE",
  "Suen (St-Martin)": "VS",
  "Sufers": "GR",
  "Sugiez": "FR",
  "Sugnens": "VD",
  "Suhr": "AG",
  "Sulgen": "TG",
  "Sullens": "VD",
  "Sulz AG": "AG",
  "Sulz LU": "LU",
  "Sulzbach": "ZH",
  "Sumiswald": "BE",
  "Summaprada": "GR",
  "Sumvitg": "GR",
  "Sundlauenen": "BE",
  "Sur": "GR",
  "Surava": "GR",
  "Surcasti": "GR",
  "Surcuolm": "GR",
  "Surin": "GR",
  "Surpierre": "FR",
  "Surrein": "GR",
  "Sursee": "LU",
  "Suscévaz": "VD",
  "Susch": "GR",
  "Susten": "VS",
  "Sutz": "BE",
  "Syens": "VD",
  "Tafers": "FR",
  "Tagelswangen": "ZH",
  "Tägerig": "AG",
  "Tägerschen": "TG",
  "Tägertschi": "BE",
  "Tägerwilen": "TG",
  "Tamins": "GR",
  "Tann": "ZH",
  "Tannay": "VD",
  "Tarasp": "GR",
  "Tartar": "GR",
  "Tartegnin": "VD",
  "Täsch": "VS",
  "Tatroz": "FR",
  "Täuffelen": "BE",
  "Tavanasa": "GR",
  "Tavannes": "BE",
  "Taverne": "TI",
  "Tecknau": "BL",
  "Tegerfelden": "AG",
  "Tegna": "TI",
  "Tenero": "TI",
  "Tenna": "GR",
  "Tenniken": "BL",
  "Tennwil": "AG",
  "Tentlingen": "FR",
  "Termen": "VS",
  "Termine": "TI",
  "Territet": "VD",
  "Tersnaus": "GR",
  "Tesserete": "TI",
  "Teufen AR": "AR",
  "Teufen ZH": "ZH",
  "Teufenthal AG": "AG",
  "Teuffenthal b. Thun": "BE",
  "Thal": "SG",
  "Thalheim AG": "AG",
  "Thalheim an der Thur": "ZH",
  "Thalkirch": "GR",
  "Thalwil": "ZH",
  "Thayngen": "SH",
  "Theilingen": "ZH",
  "Therwil": "BL",
  "Thielle": "NE",
  "Thierachern": "BE",
  "Thierrens": "VD",
  "Thônex": "GE",
  "Thörigen": "BE",
  "Thörishaus": "BE",
  "Thun": "BE",
  "Thundorf": "TG",
  "Thunstetten": "BE",
  "Thürnen": "BL",
  "Thusis": "GR",
  "Thyon": "VS",
  "Tiefencastel": "GR",
  "Tinizong": "GR",
  "Titterten": "BL",
  "Tobel": "TG",
  "Toffen": "BE",
  "Tolochenaz": "VD",
  "Toos": "TG",
  "Törbel": "VS",
  "Torgon": "VS",
  "Torny-le-Grand": "FR",
  "Torre": "TI",
  "Torricella": "TI",
  "Trachselwald": "BE",
  "Trachslau": "SZ",
  "Tramelan": "BE",
  "Trans": "GR",
  "Trasadingen": "SH",
  "Travers": "NE",
  "Treiten": "BE",
  "Trélex": "VD",
  "Tremona": "TI",
  "Trey": "VD",
  "Treycovagnes": "VD",
  "Treyfayes": "FR",
  "Treytorrens (Payerne)": "VD",
  "Treyvaux": "FR",
  "Triboltingen": "TG",
  "Triengen": "LU",
  "Trient": "VS",
  "Triesen": "FL",
  "Triesenberg": "FL",
  "Trimbach": "SO",
  "Trimmis": "GR",
  "Trimstein": "BE",
  "Trin": "GR",
  "Trin Mulin": "GR",
  "Trogen": "AR",
  "Trogne (St-Martin)": "VS",
  "Troinex": "GE",
  "Troistorrents": "VS",
  "Trub": "BE",
  "Trübbach": "SG",
  "Trubschachen": "BE",
  "Trüllikon": "ZH",
  "Trun": "GR",
  "Truttikon": "ZH",
  "Tschappina": "GR",
  "Tscheppach": "SO",
  "Tscherlach": "SG",
  "Tschiertschen": "GR",
  "Tschierv": "GR",
  "Tschingel ob Gunten": "BE",
  "Tschlin": "GR",
  "Tschugg": "BE",
  "Tübach": "SG",
  "Tuggen": "SZ",
  "Tumegl/Tomils": "GR",
  "Turbach": "BE",
  "Turbenthal": "ZH",
  "Turgi": "AG",
  "Turin (Salins)": "VS",
  "Turtmann": "VS",
  "Tüscherz-Alfermée": "BE",
  "Tuttwil": "TG",
  "Twann": "BE",
  "Udligenswil": "LU",
  "Ueberstorf": "FR",
  "Uebeschi": "BE",
  "Ueken": "AG",
  "Uerikon": "ZH",
  "Uerkheim": "AG",
  "Uerschhausen": "TG",
  "Uerzlikon": "ZH",
  "Uesslingen": "TG",
  "Uetendorf": "BE",
  "Uetikon am See": "ZH",
  "Uetliberg": "ZH",
  "Uetliburg SG": "SG",
  "Uettligen": "BE",
  "Uezwil": "AG",
  "Uffikon": "LU",
  "Ufhusen": "LU",
  "Uhwiesen": "ZH",
  "Uitikon Waldegg": "ZH",
  "Ulmiz": "FR",
  "Ulrichen": "VS",
  "Umiken": "AG",
  "Undervelier": "JU",
  "Unterägeri": "ZG",
  "Unterbach BE": "BE",
  "Unterbäch VS": "VS",
  "Unterbözberg": "AG",
  "Untereggen": "SG",
  "Unterems": "VS",
  "Unterendingen": "AG",
  "Unterengstringen": "ZH",
  "Unterentfelden": "AG",
  "Unteriberg": "SZ",
  "Unterkulm": "AG",
  "Unterlangenegg": "BE",
  "Unterlunkhofen": "AG",
  "Unterramsern": "SO",
  "Unterschächen": "UR",
  "Unterseen": "BE",
  "Untersiggenthal": "AG",
  "Unterstammheim": "ZH",
  "Untersteckholz": "BE",
  "Unterterzen": "SG",
  "Untervaz": "GR",
  "Untervaz Bahnhof": "GR",
  "Uors (Lumnezia)": "GR",
  "Urdorf": "ZH",
  "Urmein": "GR",
  "Urnäsch": "AR",
  "Urnerboden": "UR",
  "Ursenbach": "BE",
  "Ursins": "VD",
  "Urswil": "LU",
  "Ursy": "FR",
  "Urtenen-Schönbühl": "BE",
  "Uster": "ZH",
  "Uttigen": "BE",
  "Uttwil": "TG",
  "Utzenstorf": "BE",
  "Utzigen": "BE",
  "Uvrier": "VS",
  "Uznach": "SG",
  "Uzwil": "SG",
  "Vacallo": "TI",
  "Vadura": "SG",
  "Vaduz": "FL",
  "Vaglio": "TI",
  "Vairano": "TI",
  "Val-d'Illiez": "VS",
  "Valangin": "NE",
  "Valbella": "GR",
  "Valchava": "GR",
  "Valendas": "GR",
  "Valens": "SG",
  "Valeyres-sous-Montagny": "VD",
  "Valeyres-sous-Rances": "VD",
  "Valeyres-sous-Ursins": "VD",
  "Vallamand": "VD",
  "Vallon": "FR",
  "Vallorbe": "VD",
  "Vals": "GR",
  "Valzeina": "GR",
  "Vandoeuvres": "GE",
  "Varen": "VS",
  "Varenzo": "TI",
  "Vasön": "SG",
  "Vättis": "SG",
  "Vattiz": "GR",
  "Vauderens": "FR",
  "Vauffelin": "BE",
  "Vaulion": "VD",
  "Vaulruz": "FR",
  "Vaumarcus": "NE",
  "Vaux-sur-Morges": "VD",
  "Vaz/Obervaz": "GR",
  "Vella": "GR",
  "Vellerat": "JU",
  "Veltheim AG": "AG",
  "Vendlincourt": "JU",
  "Vens (Sembrancher)": "VS",
  "Venthône": "VS",
  "Verbier": "VS",
  "Vercorin": "VS",
  "Verdabbio": "GR",
  "Verdasio": "TI",
  "Vergeletto": "TI",
  "Vermes": "JU",
  "Vernamiège": "VS",
  "Vernate": "TI",
  "Vernayaz": "VS",
  "Vernier": "GE",
  "Vérossaz": "VS",
  "Vers-chez-Perrin": "VD",
  "Vers-l'Eglise": "VD",
  "Versam": "GR",
  "Verscio": "TI",
  "Versegères": "VS",
  "Versoix": "GE",
  "Vésenaz": "GE",
  "Vesin": "FR",
  "Vessy": "GE",
  "Vétroz": "VS",
  "Vevey": "VD",
  "Vex": "VS",
  "Veyras": "VS",
  "Veyrier": "GE",
  "Veysonnaz": "VS",
  "Veytaux": "VD",
  "Vezia": "TI",
  "Vezio": "TI",
  "Viano": "GR",
  "Vich": "VD",
  "Vichères (Liddes)": "VS",
  "Vico Morcote": "TI",
  "Vicosoprano": "GR",
  "Vicques": "JU",
  "Viganello": "TI",
  "Vignogn": "GR",
  "Vilars NE": "NE",
  "Villa (Ayent)": "VS",
  "Villa Bedretto": "TI",
  "Villa Luganese": "TI",
  "Villaraboud": "FR",
  "Villarbeney": "FR",
  "Villard-sur-Chamby": "VD",
  "Villarepos": "FR",
  "Villargiroud": "FR",
  "Villariaz": "FR",
  "Villarimboud": "FR",
  "Villarlod": "FR",
  "Villars-Bozon": "VD",
  "Villars-Bramard": "VD",
  "Villars-Burquin": "VD",
  "Villars-Epeney": "VD",
  "Villars-le-Comte": "VD",
  "Villars-le-Grand": "VD",
  "Villars-le-Terroir": "VD",
  "Villars-Mendraz": "VD",
  "Villars-sous-Champvent": "VD",
  "Villars-sous-Mont": "FR",
  "Villars-sous-Yens": "VD",
  "Villars-Ste-Croix": "VD",
  "Villars-sur Fontenais": "JU",
  "Villars-sur-Glâne": "FR",
  "Villars-sur-Ollon": "VD",
  "Villars-Tiercelin": "VD",
  "Villarsel-le-Gibloux": "FR",
  "Villarsel-sur-Marly": "FR",
  "Villarsiviriaux": "FR",
  "Villarvolard": "FR",
  "Villarzel": "VD",
  "Villaz-St-Pierre": "FR",
  "Villeneuve FR": "FR",
  "Villeneuve VD": "VD",
  "Villeret": "BE",
  "Villette (Lavaux)": "VD",
  "Villette (Le Châble VS)": "VS",
  "Villiers": "NE",
  "Villigen": "AG",
  "Villmergen": "AG",
  "Villnachern": "AG",
  "Vilters": "SG",
  "Vinelz": "BE",
  "Vinzel": "VD",
  "Vionnaz": "VS",
  "Vira (Gambarogno)": "TI",
  "Visp": "VS",
  "Visperterminen": "VS",
  "Vissoie": "VS",
  "Vitznau": "LU",
  "Vnà": "GR",
  "Vogorno": "TI",
  "Volken": "ZH",
  "Volketswil": "ZH",
  "Vollèges": "VS",
  "Vordemwald": "AG",
  "Vorderthal": "SZ",
  "Vouvry": "VS",
  "Vrin": "GR",
  "Vuadens": "FR",
  "Vuarmarens": "FR",
  "Vuarrens": "VD",
  "Vucherens": "VD",
  "Vufflens-la-Ville": "VD",
  "Vufflens-le-Château": "VD",
  "Vugelles-La Mothe": "VD",
  "Vuibroye": "VD",
  "Vuippens": "FR",
  "Vuisternens-devant-Romont": "FR",
  "Vuisternens-en-Ogoz": "FR",
  "Vuiteboeuf": "VD",
  "Vulliens": "VD",
  "Vullierens": "VD",
  "Vulpera": "GR",
  "Wabern": "BE",
  "Wädenswil": "ZH",
  "Wagen": "SG",
  "Wagenhausen": "TG",
  "Wagerswil": "TG",
  "Wahlen b. Laufen": "BL",
  "Wahlendorf": "BE",
  "Walchwil": "ZG",
  "Wald AR": "AR",
  "Wald ZH": "ZH",
  "Walde AG": "AG",
  "Walde SG": "SG",
  "Waldenburg": "BL",
  "Waldhäusern AG": "AG",
  "Wäldi": "TG",
  "Waldkirch": "SG",
  "Waldstatt": "AR",
  "Walenstadt": "SG",
  "Walenstadtberg": "SG",
  "Walkringen": "BE",
  "Wallbach": "AG",
  "Wallenbuch": "FR",
  "Wallenried": "FR",
  "Wallenwil": "TG",
  "Wallisellen": "ZH",
  "Walliswil b. Niederbipp": "BE",
  "Walliswil b. Wangen": "BE",
  "Walperswil": "BE",
  "Waltalingen": "ZH",
  "Waltensburg/Vuorz": "GR",
  "Waltenschwil": "AG",
  "Walterswil BE": "BE",
  "Walterswil SO": "SO",
  "Walzenhausen": "AR",
  "Wangen an der Aare": "BE",
  "Wangen b. Dübendorf": "ZH",
  "Wangen b. Olten": "SO",
  "Wangen SZ": "SZ",
  "Wangenried": "BE",
  "Wängi": "TG",
  "Wangs": "SG",
  "Wanzwil": "BE",
  "Warth": "TG",
  "Wasen im Emmental": "BE",
  "Wassen UR": "UR",
  "Wasserauen": "AI",
  "Wasterkingen": "ZH",
  "Watt": "ZH",
  "Wattenwil": "BE",
  "Wauwil": "LU",
  "Wavre": "NE",
  "Weesen": "SG",
  "Wegenstetten": "AG",
  "Weggis": "LU",
  "Weiach": "ZH",
  "Weier im Emmental": "BE",
  "Weinfelden": "TG",
  "Weingarten-Kalthäusern": "TG",
  "Weiningen TG": "TG",
  "Weiningen ZH": "ZH",
  "Weissbad": "AI",
  "Weissenburg": "BE",
  "Weissenstein b. Solothurn": "SO",
  "Weisslingen": "ZH",
  "Weisstannen": "SG",
  "Weite": "SG",
  "Welschenrohr": "SO",
  "Wengen": "BE",
  "Wengi b. Büren": "BE",
  "Wengi b. Frutigen": "BE",
  "Wenslingen": "BL",
  "Werdenberg": "SG",
  "Wergenstein": "GR",
  "Wermatswil": "ZH",
  "Wernetshausen": "ZH",
  "Werthenstein": "LU",
  "Wettingen": "AG",
  "Wettswil": "ZH",
  "Wetzikon TG": "TG",
  "Wetzikon ZH": "ZH",
  "Wichtrach": "BE",
  "Widen": "AG",
  "Widnau": "SG",
  "Wiedlisbach": "BE",
  "Wienacht-Tobel": "AR",
  "Wiesen GR": "GR",
  "Wiesenberg": "NW",
  "Wiesendangen": "ZH",
  "Wiezikon b. Sirnach": "TG",
  "Wiggen": "LU",
  "Wiggiswil": "BE",
  "Wigoltingen": "TG",
  "Wikon": "LU",
  "Wil AG": "AG",
  "Wil SG": "SG",
  "Wil ZH": "ZH",
  "Wila": "ZH",
  "Wilchingen": "SH",
  "Wildberg": "ZH",
  "Wildegg": "AG",
  "Wildensbuch": "ZH",
  "Wilderswil": "BE",
  "Wilen (Gottshaus)": "TG",
  "Wilen (Sarnen)": "OW",
  "Wilen b. Neunforn": "TG",
  "Wilen b. Wil": "TG",
  "Wilen b. Wollerau": "SZ",
  "Wiler (Lötschen)": "VS",
  "Wiler b. Seedorf": "BE",
  "Wiler b. Utzenstorf": "BE",
  "Wileroltigen": "BE",
  "Wiliberg": "AG",
  "Wilihof": "LU",
  "Willadingen": "BE",
  "Willerzell": "SZ",
  "Willisau": "LU",
  "Willisdorf": "TG",
  "Wimmis": "BE",
  "Winden": "TG",
  "Windisch": "AG",
  "Windlach": "ZH",
  "Winikon": "LU",
  "Winistorf": "SO",
  "Winkel": "ZH",
  "Winterberg ZH": "ZH",
  "Wintersingen": "BL",
  "Winterthur": "ZH",
  "Winznau": "SO",
  "Wirzweli": "NW",
  "Wisen SO": "SO",
  "Wislikofen": "AG",
  "Wittenbach": "SG",
  "Wittenwil": "TG",
  "Witterswil": "SO",
  "Wittinsburg": "BL",
  "Wittnau": "AG",
  "Wittwil": "AG",
  "Wohlen AG": "AG",
  "Wohlen b. Bern": "BE",
  "Wohlenschwil": "AG",
  "Wolfenschiessen": "NW",
  "Wolfertswil": "SG",
  "Wolfhalden": "AR",
  "Wolfhausen": "ZH",
  "Wolfisberg": "BE",
  "Wölflinswil": "AG",
  "Wolfwil": "SO",
  "Wolhusen": "LU",
  "Wollerau": "SZ",
  "Worb": "BE",
  "Worben": "BE",
  "Worblaufen": "BE",
  "Wöschnau": "SO",
  "Wünnewil": "FR",
  "Wuppenau": "TG",
  "Würenlingen": "AG",
  "Würenlos": "AG",
  "Wynau": "BE",
  "Wynigen": "BE",
  "Wyssachen": "BE",
  "Yens": "VD",
  "Yverdon-les-Bains": "VD",
  "Yvonand": "VD",
  "Yvorne": "VD",
  "Zauggenried": "BE",
  "Zäziwil": "BE",
  "Zeglingen": "BL",
  "Zeihen": "AG",
  "Zeiningen": "AG",
  "Zelg (Wolfhalden)": "AR",
  "Zell LU": "LU",
  "Zell ZH": "ZH",
  "Zénauva": "FR",
  "Zeneggen": "VS",
  "Zermatt": "VS",
  "Zernez": "GR",
  "Zetzwil": "AG",
  "Zezikon": "TG",
  "Ziefen": "BL",
  "Ziegelbrücke": "GL",
  "Zielebach": "BE",
  "Zignau": "GR",
  "Zihlschlacht": "TG",
  "Zillis": "GR",
  "Zimmerwald": "BE",
  "Zinal": "VS",
  "Zizers": "GR",
  "Zofingen": "AG",
  "Zollbrück": "BE",
  "Zollikerberg": "ZH",
  "Zollikofen": "BE",
  "Zollikon": "ZH",
  "Zuben": "TG",
  "Züberwangen": "SG",
  "Zuckenriet": "SG",
  "Zufikon": "AG",
  "Zug": "ZG",
  "Zugerberg": "ZG",
  "Zullwil": "SO",
  "Zumholz": "FR",
  "Zumikon": "ZH",
  "Zunzgen": "BL",
  "Zuoz": "GR",
  "Zürich": "ZH",
  "Zuzgen": "AG",
  "Zuzwil BE": "BE",
  "Zuzwil SG": "SG",
  "Zweidlen": "ZH",
  "Zweilütschinen": "BE",
  "Zweisimmen": "BE",
  "Zwieselberg": "BE",
  "Zwillikon": "ZH",
  "Zwingen": "BL",
  "Zwischenflüh": "BE"
};

export const kantone = [
  'AG', 'AI', 'AR', 'BE', 'BL', 'BS', 'FL', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SO', 'SZ', 'TG', 'TI', 'UR', 'VD', 'VS', 'ZG', 'ZH'
] as const;

export type Kanton = typeof kantone[number];

export const kantonNamen: Record<Kanton, string> = {
  'AG': 'Aargau',
  'AI': 'Appenzell Innerrhoden',
  'AR': 'Appenzell Ausserrhoden',
  'BE': 'Bern',
  'BL': 'Basel-Landschaft',
  'BS': 'Basel-Stadt',
  'FL': 'Fürstentum Liechtenstein',
  'FR': 'Freiburg',
  'GE': 'Genf',
  'GL': 'Glarus',
  'GR': 'Graubünden',
  'JU': 'Jura',
  'LU': 'Luzern',
  'NE': 'Neuenburg',
  'NW': 'Nidwalden',
  'OW': 'Obwalden',
  'SG': 'St. Gallen',
  'SH': 'Schaffhausen',
  'SO': 'Solothurn',
  'SZ': 'Schwyz',
  'TG': 'Thurgau',
  'TI': 'Tessin',
  'UR': 'Uri',
  'VD': 'Waadt',
  'VS': 'Wallis',
  'ZG': 'Zug',
  'ZH': 'Zürich'
} as const;

export function getKantonForOrt(ort: string): Kanton | undefined {
  return ortschaftZuKanton[ort] as Kanton | undefined;
}
