services:
  - type: web
    name: surveyjobs-backend
    env: node
    buildCommand: |
      npm install
      rm -rf dist/
      npm run build
      echo "=== Build Output ==="
      ls -la dist/
      if [ ! -f dist/index.js ]; then
        echo "ERROR: dist/index.js wurde nicht erstellt!"
        exit 1
      fi
      echo "=== End Build Output ==="
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false 